### ISSUE TITLE
Error: Device Is Offline

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [twrecked/hass-aarlo#145]
I am currently using this component within a Docker environment (not HASS.io) behind a reverse proxy (Traefik).

Since the latest version of Home Assistant (103.6) and the AArlo component (0.6.7), I keep seeing these errors:

`WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}`

All my devices seem to appear, but nothing is updated.

**Comment by twrecked** [comment]
I'm on 0.6.7 and not seeing this. It's not the network because this is a message coming back form the Arlo servers.

Can you try logging into https://my.arlo.com/#/home with your Home Assistant Arlo account and see if the cameras appear there?

**Comment by danieledwardgeorgehitchcock** [comment]
I have just logged on using my Home Assistant Arlo account and no devices are showing as being offline.

One interesting thing is that my Arlo Baby is showing as requiring an updated version of Flash - Could this be what is causing the error to be returned?

**Comment by twrecked** [comment]
I've never seen that error before but the update could be causing the error.

Did you give admin access to your HA Arlo account? That might cause a problem too.

**Comment by sbowater** [comment]
I was getting these same errors earlier today.  Then I realized that I had renamed some of my devices in the Arlo app which led to some ghost entities in HA.  I don't know if this is related (may just be coincidence) but after I deleted these old named entities and restarted no more errors.

**Comment by twrecked** [comment]
The code doesn't handle name changes particularity well. The original code I based it on provided the name as part of the device ID but I might add an option to use the serial number of the device. 

This would keep name changes easier.

**Comment by danieledwardgeorgehitchcock** [comment]
I haven't changed any names since I started using the Home Assistant Aarlo integration however, A restart seems to have cleared the errors up for me.

**Comment by twrecked** [comment]
I'm going to close this for now. I've fixed the docs around naming and have a version of the code optionally using device_ids ready to go.

**Comment by skynet01** [comment]
Hmm i am still getting these errors and i haven't renamed devices. Anyway i can find these ghost devices :) ?

**Comment by twrecked** [comment]
We have to dig through the debug unfortunately. Which version of Aarlo are you using?

**Comment by skynet01** [comment]
The latest one, I started noticing this about a week ago. But I assume it might have been longer. The cameras do work and show up properly

**Comment by twrecked** [comment]
0.6 or 0.7-alpha? Sorry to be pedantic but the debug is slightly different.

You can still turn this on. I need traces shortly before the error appears.

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    pyaarlo: debug
```

**Comment by skynet01** [comment]
I am on 0.6, i turned on error reporting. Attached is my aarlo debug log. Thank you so much for taking a look at it.
`2020-05-12 19:09:17 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for aarlo which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
2020-05-12 19:09:24 INFO (MainThread) [homeassistant.setup] Setting up aarlo
2020-05-12 19:09:24 DEBUG (SyncWorker_13) [pyaarlo] Cfg started
2020-05-12 19:09:24 DEBUG (SyncWorker_13) [pyaarlo] starting
2020-05-12 19:09:24 DEBUG (SyncWorker_13) [pyaarlo] custom connections 5:10
2020-05-12 19:09:27 DEBUG (ArloEventStream) [pyaarlo] starting event loop
2020-05-12 19:09:27 DEBUG (ArloEventStream) [pyaarlo] starting stream with 180.0 timeout
2020-05-12 19:09:27 DEBUG (SyncWorker_13) [pyaarlo] automatically reconnecting
2020-05-12 19:09:27 INFO (SyncWorker_13) [pyaarlo] pyaarlo starting
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU188SB6F44B/deviceId=5KU188SB6F44B
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU188SB6F44B/deviceName=Patio
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU188SB6F44B/deviceType=arloqs
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU188SB6F44B/mediaObjectCount=3593
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU188SB6F44B/parentId=5KU188SB6F44B
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU188SB6F44B/uniqueId=QXHG-100-40937845_5KU188SB6F44B
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU188SB6F44B/userId=QWYHT-336-47900775
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU188SB6F44B/presignedLastImageUrl=https://arlolastimage-z2.s3.ama
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU188SB6F44B/presignedFullFrameSnapshotUrl=https://arlos3-prod-z2.
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU188SB6F44B/xCloudId=2S92G-1660-336-111484514
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU188SB6F44B/deviceId=5KU188SB6F44B
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU188SB6F44B/deviceName=Patio
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU188SB6F44B/deviceType=arloqs
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU188SB6F44B/mediaObjectCount=3593
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU188SB6F44B/parentId=5KU188SB6F44B
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU188SB6F44B/uniqueId=QXHG-100-40937845_5KU188SB6F44B
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU188SB6F44B/userId=QWYHT-336-47900775
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU188SB6F44B/presignedLastImageUrl=https://arlolastimage-z2.s3.a
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU188SB6F44B/presignedFullFrameSnapshotUrl=https://arlos3-prod-z
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU188SB6F44B/xCloudId=2S92G-1660-336-111484514
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] parent is 5KU188SB6F44B
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU18CS08A1B9/deviceId=5KU18CS08A1B9
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU18CS08A1B9/deviceName=Front
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU18CS08A1B9/deviceType=arloqs
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU18CS08A1B9/mediaObjectCount=14145
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU18CS08A1B9/parentId=5KU18CS08A1B9
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU18CS08A1B9/uniqueId=QXHG-100-40937845_5KU18CS08A1B9
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU18CS08A1B9/userId=QWYHT-336-47900775
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU18CS08A1B9/presignedLastImageUrl=https://arlolastimage-z2.s3.ama
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU18CS08A1B9/presignedFullFrameSnapshotUrl=https://arlos3-prod-z2.
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloBase/5KU18CS08A1B9/xCloudId=9UKUNWMU-1660-336-109753535
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/deviceId=5KU18CS08A1B9
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/deviceName=Front
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/deviceType=arloqs
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/mediaObjectCount=14145
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/parentId=5KU18CS08A1B9
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/uniqueId=QXHG-100-40937845_5KU18CS08A1B9
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/userId=QWYHT-336-47900775
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/presignedLastImageUrl=https://arlolastimage-z2.s3.a
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/presignedFullFrameSnapshotUrl=https://arlos3-prod-z
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/xCloudId=9UKUNWMU-1660-336-109753535
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] parent is 5KU18CS08A1B9
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ARLO/totalCameras=2
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ARLO/totalDoorBells=0
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] set:ARLO/totalLights=0
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] getting initial settings
2020-05-12 19:09:28 DEBUG (SyncWorker_13) [pyaarlo] registering cron jobs
2020-05-12 19:09:28 DEBUG (ArloEventStream) [pyaarlo] sending mediaUploadNotification to 5KU18CS08A1B9
2020-05-12 19:09:28 DEBUG (ArloEventStream) [pyaarlo] Front BASE got mediaUploadNotification
2020-05-12 19:09:28 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one mediaUploadNotification
2020-05-12 19:09:28 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/mediaObjectCount=14146
2020-05-12 19:09:28 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/presignedLastImageUrl=https://arlos3-prod-z2.s3.ama
2020-05-12 19:09:28 DEBUG (ArloEventStream) [pyaarlo] Front thumbnail changed
2020-05-12 19:09:28 DEBUG (ArloEventStream) [pyaarlo] queing image update
2020-05-12 19:09:28 DEBUG (ArloEventStream) [pyaarlo] recording stopped, updating library
2020-05-12 19:09:28 DEBUG (ArloEventStream) [pyaarlo] queueing image library update
2020-05-12 19:09:28 DEBUG (ArloEventStream) [pyaarlo] turning recent ON for Front
2020-05-12 19:09:28 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:09:29 DEBUG (ArloBackgroundWorker) [pyaarlo] getting image for Front
2020-05-12 19:09:29 INFO (MainThread) [homeassistant.setup] Setup of domain aarlo took 5.1 seconds.
2020-05-12 19:09:29 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastImageSource=capture/05-12 19:09
2020-05-12 19:09:29 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastCapture=05-12 19:09
2020-05-12 19:09:29 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/presignedLastImageData=b'\xff\xd8\xff\xe0\x00\x10JF
2020-05-12 19:09:29 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/activityState=idle
2020-05-12 19:09:30 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.aarlo
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] updating image library
2020-05-12 19:09:30 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Patio created
2020-05-12 19:09:30 INFO (MainThread) [custom_components.aarlo.binary_sensor] ArloBinarySensor: Motion Front created
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T19:09:00
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T19:02:06
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T18:55:34
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T18:20:43
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T18:08:53
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T18:00:43
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T17:59:21
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T17:57:51
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T17:56:47
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T17:23:50
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T17:17:33
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T17:14:54
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T17:14:25
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T16:59:26
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T16:40:36
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T16:39:17
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU188SB6F44B:2020-05-12T16:33:07
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T16:27:48
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T16:09:08
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU188SB6F44B:2020-05-12T15:23:23
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T14:48:46
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T14:02:00
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T13:54:27
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T13:53:36
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T13:46:04
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T12:50:00
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU188SB6F44B:2020-05-12T12:34:07
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T12:16:14
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T12:14:47
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T11:43:18
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T11:41:40
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T11:41:02
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T11:37:50
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T11:19:39
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T11:14:49
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T11:08:10
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T11:07:07
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T10:28:08
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T09:51:10
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T09:44:05
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T09:27:22
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T09:01:30
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T07:52:46
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T07:33:45
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T03:45:50
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T03:41:55
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T03:36:18
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T03:34:58
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T02:26:39
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU188SB6F44B:2020-05-12T02:17:06
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T01:57:19
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] ml:update-count=1
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] reloading cache for Front
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/capturedToday=47
2020-05-12 19:09:30 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastCapture=05-12 19:09
2020-05-12 19:09:31 INFO (MainThread) [homeassistant.components.alarm_control_panel] Setting up alarm_control_panel.aarlo
2020-05-12 19:09:31 INFO (MainThread) [custom_components.aarlo.alarm_control_panel] ArloBaseStation: Patio created
2020-05-12 19:09:31 INFO (MainThread) [custom_components.aarlo.alarm_control_panel] ArloBaseStation: Front created
2020-05-12 19:09:31 INFO (MainThread) [custom_components.aarlo.alarm_control_panel] installing handlers
2020-05-12 19:09:33 INFO (MainThread) [homeassistant.components.camera] Setting up camera.aarlo
2020-05-12 19:09:33 INFO (MainThread) [custom_components.aarlo.camera] ArloCam: Patio created
2020-05-12 19:09:33 INFO (MainThread) [custom_components.aarlo.camera] ArloCam: Front created
2020-05-12 19:09:33 INFO (MainThread) [custom_components.aarlo.camera] installing handlers
2020-05-12 19:09:33 DEBUG (ArloBackgroundWorker) [pyaarlo] queing image update
2020-05-12 19:09:33 DEBUG (ArloBackgroundWorker) [pyaarlo] queing image update
2020-05-12 19:09:33 DEBUG (ArloBackgroundWorker) [pyaarlo] queing media update
2020-05-12 19:09:33 DEBUG (ArloBackgroundWorker) [pyaarlo] queing media update
2020-05-12 19:09:33 DEBUG (ArloBackgroundWorker) [pyaarlo] getting image for Patio
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU188SB6F44B/lastImageSource=capture/05-12 16:33
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU188SB6F44B/lastCapture=05-12 16:33
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU188SB6F44B/presignedLastImageData=b'\xff\xd8\xff\xe0\x00\x10JF
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Patio:presignedLastImageData:b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00\x00\x01\x00\x01\x00\x00\xff\xfe\x
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU188SB6F44B/activityState=idle
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Patio:activityState:idle
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] getting image for Front
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastImageSource=capture/05-12 19:09
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastCapture=05-12 19:09
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/presignedLastImageData=b'\xff\xd8\xff\xe0\x00\x10JF
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Front:presignedLastImageData:b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00\x00\x01\x00\x01\x00\x00\xff\xfe\x
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/activityState=idle
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Front:activityState:idle
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] reloading cache for Patio
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU188SB6F44B/capturedToday=4
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU188SB6F44B/lastCapture=05-12 16:33
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Patio:mediaUploadNotification:True
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] reloading cache for Front
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/capturedToday=47
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastCapture=05-12 19:09
2020-05-12 19:09:34 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Front:mediaUploadNotification:True
2020-05-12 19:09:36 DEBUG (ArloBackgroundWorker) [pyaarlo] initial refresh
2020-05-12 19:09:36 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:11:10 DEBUG (ArloEventStream) [pyaarlo] sseclient-error=ChunkedEncodingError
2020-05-12 19:11:14 DEBUG (ArloEventStream) [pyaarlo] Fetching device list after ev-reconnect
2020-05-12 19:11:27 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:11:27 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:11:27 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/motionDetected=True
2020-05-12 19:11:27 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:11:27 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/motionDetected=True
2020-05-12 19:11:27 DEBUG (ArloEventStream) [custom_components.aarlo.binary_sensor] callback:Motion Front:motionDetected:True
2020-05-12 19:11:28 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:11:28 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:11:28 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/activityState=alertStreamActive
2020-05-12 19:11:28 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:11:28 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/activityState=alertStreamActive
2020-05-12 19:11:28 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:activityState:alertStreamActive
2020-05-12 19:11:28 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:11:28 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:11:28 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:11:36 DEBUG (ArloBackgroundWorker) [pyaarlo] job-error=AttributeError
2020-05-12 19:11:36 DEBUG (ArloBackgroundWorker) [pyaarlo] loading image library
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] ml:load-count=2
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] reloading cache for Patio
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU188SB6F44B/capturedToday=4
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU188SB6F44B/lastCapture=05-12 16:33
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Patio:mediaUploadNotification:True
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] reloading cache for Front
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/capturedToday=47
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastCapture=05-12 19:09
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Front:mediaUploadNotification:True
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-05-12!
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-05-12 19:11:37 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-05-12!
2020-05-12 19:11:37 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:11:38 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:11:46 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:11:46 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:11:46 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/motionDetected=False
2020-05-12 19:11:46 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:11:46 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/motionDetected=False
2020-05-12 19:11:46 DEBUG (ArloEventStream) [custom_components.aarlo.binary_sensor] callback:Motion Front:motionDetected:False
2020-05-12 19:11:47 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:11:47 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:11:47 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/activityState=idle
2020-05-12 19:11:47 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:11:47 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/activityState=idle
2020-05-12 19:11:47 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:activityState:idle
2020-05-12 19:11:47 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:11:47 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:11:47 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:12:00 DEBUG (ArloEventStream) [pyaarlo] sending mediaUploadNotification to 5KU18CS08A1B9
2020-05-12 19:12:00 DEBUG (ArloEventStream) [pyaarlo] Front BASE got mediaUploadNotification
2020-05-12 19:12:00 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one mediaUploadNotification
2020-05-12 19:12:00 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/mediaObjectCount=14147
2020-05-12 19:12:00 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/presignedLastImageUrl=https://arlos3-prod-z2.s3.ama
2020-05-12 19:12:00 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:presignedLastImageUrl:https://arlos3-prod-z2.s3.amazonaws.com/d721e1ee645e4f9a94febf5ee445c314/QXHG-10
2020-05-12 19:12:00 DEBUG (ArloEventStream) [pyaarlo] Front thumbnail changed
2020-05-12 19:12:00 DEBUG (ArloEventStream) [pyaarlo] queing image update
2020-05-12 19:12:00 DEBUG (ArloEventStream) [pyaarlo] recording stopped, updating library
2020-05-12 19:12:00 DEBUG (ArloBackgroundWorker) [pyaarlo] getting image for Front
2020-05-12 19:12:00 DEBUG (ArloEventStream) [pyaarlo] queueing image library update
2020-05-12 19:12:00 DEBUG (ArloEventStream) [pyaarlo] turning recent ON for Front
2020-05-12 19:12:00 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:recentActivity:True
2020-05-12 19:12:01 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastImageSource=capture/05-12 19:11
2020-05-12 19:12:01 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastCapture=05-12 19:11
2020-05-12 19:12:01 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/presignedLastImageData=b'\xff\xd8\xff\xe0\x00\x10JF
2020-05-12 19:12:01 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Front:presignedLastImageData:b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00\x00\x01\x00\x01\x00\x00\xff\xfe\x
2020-05-12 19:12:01 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/activityState=idle
2020-05-12 19:12:01 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Front:activityState:idle
2020-05-12 19:12:02 DEBUG (ArloBackgroundWorker) [pyaarlo] updating image library
2020-05-12 19:12:02 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T19:11:26
2020-05-12 19:12:02 DEBUG (ArloBackgroundWorker) [pyaarlo] ml:update-count=3
2020-05-12 19:12:02 DEBUG (ArloBackgroundWorker) [pyaarlo] reloading cache for Front
2020-05-12 19:12:02 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/capturedToday=48
2020-05-12 19:12:02 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastCapture=05-12 19:11
2020-05-12 19:12:02 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Front:mediaUploadNotification:True
2020-05-12 19:12:28 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-05-12 19:12:28 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-05-12!
2020-05-12 19:12:28 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:13:28 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-05-12 19:13:28 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-05-12!
2020-05-12 19:13:28 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/motionDetected=True
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/motionDetected=True
2020-05-12 19:14:22 DEBUG (ArloEventStream) [custom_components.aarlo.binary_sensor] callback:Motion Front:motionDetected:True
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/activityState=alertStreamActive
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:14:22 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/activityState=alertStreamActive
2020-05-12 19:14:22 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:activityState:alertStreamActive
2020-05-12 19:14:28 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-05-12 19:14:28 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-05-12!
2020-05-12 19:14:28 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:14:37 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:14:37 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:14:37 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/motionDetected=False
2020-05-12 19:14:37 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:14:37 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/motionDetected=False
2020-05-12 19:14:37 DEBUG (ArloEventStream) [custom_components.aarlo.binary_sensor] callback:Motion Front:motionDetected:False
2020-05-12 19:14:37 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:14:37 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:14:37 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/activityState=idle
2020-05-12 19:14:37 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:14:37 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/activityState=idle
2020-05-12 19:14:37 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:activityState:idle
2020-05-12 19:14:38 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:14:38 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:14:38 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:14:50 DEBUG (ArloEventStream) [pyaarlo] sending mediaUploadNotification to 5KU18CS08A1B9
2020-05-12 19:14:50 DEBUG (ArloEventStream) [pyaarlo] Front BASE got mediaUploadNotification
2020-05-12 19:14:50 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one mediaUploadNotification
2020-05-12 19:14:50 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/mediaObjectCount=14148
2020-05-12 19:14:50 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/presignedLastImageUrl=https://arlos3-prod-z2.s3.ama
2020-05-12 19:14:50 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:presignedLastImageUrl:https://arlos3-prod-z2.s3.amazonaws.com/d721e1ee645e4f9a94febf5ee445c314/QXHG-10
2020-05-12 19:14:50 DEBUG (ArloEventStream) [pyaarlo] Front thumbnail changed
2020-05-12 19:14:50 DEBUG (ArloEventStream) [pyaarlo] queing image update
2020-05-12 19:14:50 DEBUG (ArloEventStream) [pyaarlo] recording stopped, updating library
2020-05-12 19:14:50 DEBUG (ArloEventStream) [pyaarlo] queueing image library update
2020-05-12 19:14:50 DEBUG (ArloEventStream) [pyaarlo] turning recent ON for Front
2020-05-12 19:14:50 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:recentActivity:True
2020-05-12 19:14:50 DEBUG (ArloBackgroundWorker) [pyaarlo] getting image for Front
2020-05-12 19:14:51 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastImageSource=capture/05-12 19:14
2020-05-12 19:14:51 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastCapture=05-12 19:14
2020-05-12 19:14:51 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/presignedLastImageData=b'\xff\xd8\xff\xe0\x00\x10JF
2020-05-12 19:14:51 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Front:presignedLastImageData:b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x02\x00\x00\x01\x00\x01\x00\x00\xff\xfe\x
2020-05-12 19:14:51 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/activityState=idle
2020-05-12 19:14:51 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Front:activityState:idle
2020-05-12 19:14:52 DEBUG (ArloBackgroundWorker) [pyaarlo] updating image library
2020-05-12 19:14:52 DEBUG (ArloBackgroundWorker) [pyaarlo] adding 5KU18CS08A1B9:2020-05-12T19:14:22
2020-05-12 19:14:52 DEBUG (ArloBackgroundWorker) [pyaarlo] ml:update-count=4
2020-05-12 19:14:52 DEBUG (ArloBackgroundWorker) [pyaarlo] reloading cache for Front
2020-05-12 19:14:52 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/capturedToday=49
2020-05-12 19:14:52 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/lastCapture=05-12 19:14
2020-05-12 19:14:52 DEBUG (ArloBackgroundWorker) [custom_components.aarlo.camera] callback:Front:mediaUploadNotification:True
2020-05-12 19:15:28 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-05-12 19:15:28 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-05-12!
2020-05-12 19:15:28 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:16:28 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-05-12 19:16:28 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-05-12!
2020-05-12 19:16:28 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:17:28 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-05-12 19:17:28 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-05-12!
2020-05-12 19:17:28 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:18:28 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-05-12 19:18:28 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-05-12!
2020-05-12 19:18:28 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:19:28 DEBUG (ArloBackgroundWorker) [pyaarlo] fast refresh
2020-05-12 19:19:28 DEBUG (ArloBackgroundWorker) [pyaarlo] day testing with 2020-05-12!
2020-05-12 19:19:28 DEBUG (ArloBackgroundWorker) [pyaarlo] slow refresh
2020-05-12 19:19:28 DEBUG (ArloBackgroundWorker) [pyaarlo] device reload check 2239832.009432521 2246431.656528271
2020-05-12 19:19:28 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:19:29 WARNING (ArloBackgroundWorker) [pyaarlo] error in response={'data': {'error': '2059', 'message': 'Device is offline.', 'reason': 'Device is offline.'}, 'success': False}
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/motionDetected=True
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/motionDetected=True
2020-05-12 19:20:09 DEBUG (ArloEventStream) [custom_components.aarlo.binary_sensor] callback:Motion Front:motionDetected:True
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/activityState=alertStreamActive
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:20:09 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/activityState=alertStreamActive
2020-05-12 19:20:09 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:activityState:alertStreamActive
2020-05-12 19:20:24 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:20:24 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:20:24 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/motionDetected=False
2020-05-12 19:20:24 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:20:24 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/motionDetected=False
2020-05-12 19:20:24 DEBUG (ArloEventStream) [custom_components.aarlo.binary_sensor] callback:Motion Front:motionDetected:False
2020-05-12 19:20:24 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:20:24 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:20:24 DEBUG (ArloEventStream) [pyaarlo] set:ArloBase/5KU18CS08A1B9/activityState=idle
2020-05-12 19:20:24 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:20:24 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/activityState=idle
2020-05-12 19:20:24 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:activityState:idle
2020-05-12 19:20:25 DEBUG (ArloEventStream) [pyaarlo] sending cameras/5KU18CS08A1B9 to 5KU18CS08A1B9
2020-05-12 19:20:25 DEBUG (ArloEventStream) [pyaarlo] Front BASE got cameras/5KU18CS08A1B9
2020-05-12 19:20:25 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one cameras/5KU18CS08A1B9
2020-05-12 19:20:39 DEBUG (ArloEventStream) [pyaarlo] sending mediaUploadNotification to 5KU18CS08A1B9
2020-05-12 19:20:39 DEBUG (ArloEventStream) [pyaarlo] Front BASE got mediaUploadNotification
2020-05-12 19:20:39 DEBUG (ArloEventStream) [pyaarlo] Front CAMERA got one mediaUploadNotification
2020-05-12 19:20:39 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/mediaObjectCount=14149
2020-05-12 19:20:39 DEBUG (ArloEventStream) [pyaarlo] set:ArloCamera/5KU18CS08A1B9/presignedLastImageUrl=https://arlos3-prod-z2.s3.ama
2020-05-12 19:20:39 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:presignedLastImageUrl:https://arlos3-prod-z2.s3.amazonaws.com/d721e1ee645e4f9a94febf5ee445c314/QXHG-10
2020-05-12 19:20:39 DEBUG (ArloEventStream) [pyaarlo] Front thumbnail changed
2020-05-12 19:20:39 DEBUG (ArloEventStream) [pyaarlo] queing image update
2020-05-12 19:20:39 DEBUG (ArloEventStream) [pyaarlo] recording stopped, updating library
2020-05-12 19:20:39 DEBUG (ArloEventStream) [pyaarlo] queueing image library update
2020-05-12 19:20:39 DEBUG (ArloEventStream) [pyaarlo] turning recent ON for Front
2020-05-12 19:20:39 DEBUG (ArloEventStream) [custom_components.aarlo.camera] callback:Front:recentActivity:True
`

**Comment by twrecked** [comment]
Do the Arlo Qs appear as 2 base stations?

Are you ok trying a beta release? The debug is better and I can get a list of devices you have dumped straight into the logs. My best theory is the code is trying to ping a device that it shouldn't.
Add this to your config and you will get packet dumps into the logs of everything that arrives in the system, look for `devices=`.

```
aarlo:
  verbose_debug: True
```

Even without that I noticed a couple of strange things.  This error appears, it means there was an issue with the event stream:
```
2020-05-12 19:11:10 DEBUG (ArloEventStream) [pyaarlo] sseclient-error=ChunkedEncodingError 
```

This appears. I don't know what this is about because I left the message a little too cryptic.
```
2020-05-12 19:11:36 DEBUG (ArloBackgroundWorker) [pyaarlo] job-error=AttributeError
```

I'm still looking.

**Comment by skynet01** [comment]
No they show up as normal cameras no base stations. It used to work fine, and log error only started happening about a 3-4 weeks ago. I am ok trying the beta release, should i switch to 0.7?

**Comment by twrecked** [comment]
I'll check through the releases and see if anything might be causing this.

In the mean time if you could try 0.7 and see what the devices= output is giving that would be great. You can always switch back.

Also, does the audio detection work on these cameras? I'm not sure I cater specifically for them.

**Comment by pr0jektcha0s** [comment]
I have this exact same issue. Do you want me to open a new issue or build off of this one?

**Comment by twrecked** [comment]
We'll build off this one. I'm also currently seeing a lot of strange errors, even using the Arlo web site and app.

**Comment by pr0jektcha0s** [comment]
Ok, I've done more investigation. I enabled logger and set aarlo into debug mode and saw what device was showing offline. My Arlo account shares between two accounts because I was using two base stations because of the number of cameras I had. Since the accounts were still connected my primary account was looking for a base station that was offline. I went in to my Arlo accounts and removed the sharing of all devices and the issue has gone away.

I don't use my Arlos for security cameras in a while since I now use POE cameras. I got these out to put out around our trees to watch the bird feeders. Didn't think about the shared account.

Thanks for the help and keep up the good work!

**Comment by toddtmw** [comment]
Hi. I am having a similar issue. I've tried many different combinations in my configuration.yaml file and what happens is when HA starts, it gets all the info from Arlo, but then it never updates again. I see thumbnails, but when I click them I get this error:
```
This entity is currently unavailable and is an orphan to a removed, changed or dysfunctional integration or device.

If the entity is no longer in use, you can clean it up by removing it.
```
Automations built of the motion detector or looking at the motion detector in the overview never shows motion being recognized.

In my binary sensor section, I have this:
```
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
```

Here are the other configurations:
```
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 1
    alarm_volume: 1
camera:
  - platform: aarlo

```
the aarlo_log.txt file attached is the log at start up.
[aarlo_log.txt](https://github.com/twrecked/hass-aarlo/files/5018172/aarlo_log.txt)

The aarlo_motion.txt file are the lines that are added to the log when I walk in front of the camera. I am getting errors, but I do not know why.
[aarlo_motion.txt](https://github.com/twrecked/hass-aarlo/files/5018185/aarlo_motion.txt)

I am running:
v0.7.0-beta.1

I have 3 Arlo Pro2 cameras, 2 Arlo Cameras that are all connected through an Arlo Pro2 Base Station.

Thank you to any assistance you can provide.

**Comment by twrecked** [comment]
Excellent, glad it's working again now!
