### ISSUE TITLE
Turn Cameras on and off?

### ISSUE THREAD

**Issue by t9001** [twrecked/hass-aarlo#283]
Possible to access this parameter?
In the app there is a toggle switch to turn cameras off.
It would be very handy to be able to turn individual cameras on and off programatically.
Use Case:
I use the modes to adjust camera sensitivity based on local wind speed.
Works like a charm. "Calm", "Normal", "Windy" and "Very Windy".
If I need to turn the front yard camera off because the kids are playing, instead of 4 modes, I now need 8. And if I need to turn the back yard camera off then it's now 16 different modes.

Many thakns for the awesome work on this!

**Comment by twrecked** [comment]
I should be able to do this. There is a "Device On/Off" button on the web interface, I'll see what it does.

**Comment by twrecked** [comment]
Turns out it's already there... (Like I keep saying, real work has been crazy and I think I've "paged out" some of my Aarlo knowledge.)

You can use the services `camera.turn_on` and `camera.turn_off` to enable and disable the camera.

There are two issues with it 
* the Lovelace card update is broken
* the status when going to off is broken

I'll look at those but it does work at the moment.

**Comment by t9001** [comment]
Doh! I’m sorry. I thought I’d looked for it carefully.

**Comment by twrecked** [comment]
No problems. And there are a couple of fixes it needs.

**Comment by twrecked** [comment]
I just checked in Aarlo 0.7.0.alpha.8 and Lovelace 0.1.3 that tidies this up. Look for `on_off` in the Lovelace docs.

**Comment by mikesalz** [comment]
Similar question... Is it possible to restart an Arlo base station as well, or is this only at the camera level?

**Comment by twrecked** [comment]
@mikesalz Not right now. I think it would be quite simple to add a restart service for base stations.

**Comment by mikesalz** [comment]
@twrecked That would be very cool if you could add that.  I don't know if other people have similar issues, but my cameras randomly decide to stop recording for days at a time until I restart the base station.  I never even know it is an issue until I try to go back and watch a recording.  If I could schedule periodic restarts using HA, that should solve my problem!

**Comment by twrecked** [comment]
@mikesalz I looked into this and I can do it, the only downside is you need to login with the main account to restart a device. I'll check in the code but be aware of the limitation.

**Comment by mikesalz** [comment]
Awesome!  I will check it out.  Thanks!

**Comment by mikesalz** [comment]
Sorry to bug you @twrecked!  I have another question, mildly related to this thread.  I have an Arlo Baby camera that sometimes stops sending motion and sound alerts to HA.  I'm not sure if that is on Arlo's end or something in the integration.  But it seems to be resolved when I restart the camera through the Arlo app or web UI.  I see the aarlo.restart_device service is available.  But when I execute the below in an automation, I don't see anything in the HA logbook and the camera doesn't really seem to do anything.  How would I know if this is actually working?

```
    - service: aarlo.restart_device
      entity_id: camera.aarlo_kids_room
```

**Comment by twrecked** [comment]
The `restart` is annoying. I implemented it but you need to be the main account to use it. It's an Arlo restriction.

You should see something in the debug log.

**Comment by mikesalz** [comment]
> you need to be the main account to use it

I switched my configuration.yaml to use my primary Arlo account, but it still does not seem to be able to restart the cameras.  I changed my logger to the following to see if I could find anything in the debug log, but debug at the HA level is just unusable because there is so much stuff.  How would I debug only aarlo?

```
logger:
  default: debug
  logs:
    homeassistant.core: debug
```

**Comment by twrecked** [comment]
The following debug should help:

https://github.com/twrecked/hass-aarlo#debugging

```yaml
logger:
  default: info
  logs:
    custom_components.aarlo: debug
    custom_components.aarlo.alarm_control_panel: debug
    pyaarlo: debug
```

**Comment by mikesalz** [comment]
Thanks @twrecked!  But there is still a ton of stuff in the log.  Should I be looking for something in particular?

**Comment by mikesalz** [comment]
Actually, I think I found the issue.  It is showing device not found for the two Arlo Baby cameras (I renamed them here because I would rather not display my kids' names).  They do show under Developer Tools with a state of Idle.

2020-10-15 11:34:53 INFO (SyncWorker_25) [custom_components.aarlo] restart_device service called
2020-10-15 11:34:53 INFO (SyncWorker_25) [custom_components.aarlo] camera.aarlo_x_room device not found
2020-10-15 11:34:53 INFO (SyncWorker_25) [custom_components.aarlo] camera.aarlo_y_room device not found

**Comment by twrecked** [comment]
This is an Arlo Baby specific issue. Do you have alarm devices enabled for those cameras? Where you arm/disarm? Can you try that device.

I'll modify the code the try the camera domain as well.

**Comment by mikesalz** [comment]
I'm not using any Arlo alarms.

**Comment by mikesalz** [comment]
Well, I guess this is confusing.  Is an alarm the same as an alert?  In the Arlo website, under the Devices tab I have the cameras set up to alert when motion or auto is detected.  But under the Mode tab I see you can Arm or Disarm devices.  I never use this, and frankly do not even know what it is for.

**Comment by twrecked** [comment]
Arlo Baby Cams are their own base stations. For most other Arlo cameras you have to connect them to a base station for them to work. The cameras and base stations appear as different entities in Home Assistant.

To make the Baby Cam work with Home Assistant we have to create 2 devices - a `camera` and an `alarm_control_panel` device. You use the camera device to stream videos, view snapshots... and the alarm device to change the mode - armed, disarmed... - and restart.

When I implemented the code I made the `restart` command only work against `alarm_control_panel` devices because you can't issue a restart against a camera. Well, any of the cameras I have anyway... Turns out you can if it's a Baby Cam.

Your choices are. Add an alarm control panel device:

```yaml
alarm_control_panel:
  - platform: aarlo
    home_mode_name: home
    away_mode_name: armed
    night_mode_name: night
```
And send the restart to `alarm_control_panel.aarlo_x_room`.

Or wait a couple of hours and I'll push a fix that allows cameras to use the restart command.

**Comment by mikesalz** [comment]
Gotcha.  This is not a restart emergency, so I can wait for the fix. :) Thank you SO much for your quick responses!  I really appreciate it!

**Comment by mikesalz** [comment]
@twrecked Just FYI - I decided to give it a try with alarm_control_panel and it is working perfectly.  I am restarting my Arlo base station and Arlo Baby cameras daily.  Seems stupid that I have to do that, but they all perform much better with daily restarts.  Thanks again for your help!
