### ISSUE TITLE
No Display - Only works on Single Dashboard

### ISSUE THREAD

**Issue by giffordj** [twrecked/hass-aarlo#297]
I have two different dashboards that have 2 different issues.

On the working dashboard, I get the controls, but no images.
On the non-working dashboard, I get nothing
![Not-Working](https://user-images.githubusercontent.com/19445255/89833471-f20dac80-db15-11ea-858c-e28c5998286f.png)
![Working](https://user-images.githubusercontent.com/19445255/89833472-f2a64300-db15-11ea-8b1d-a26c0933080b.png)
[pyarlo.log](https://github.com/twrecked/hass-aarlo/files/5053519/pyarlo.log)

in lovelace.yaml I have
#
# Resources Configuration
#
resources:
    - url: /hacsfiles/lovelace-hass-aarlo/hass-aarlo.js
      type: module

in camera.yaml I have various entries like
  - type: 'custom:aarlo-glance'
    entity: camera.aarlo_mailbox
    name: Mailbox
    show:
      - motion
      - sound
      - snapshot
      - battery_level
      - signal_strength
      - captured_today
      - image_date
    image_click: play
  - type: 'custom:aarlo-glance'

**Comment by twrecked** [comment]
First off - thank you for the log, you're the first to send me an encrypted one and it worked!

There is a bug dealing with the base stations and it's causing a crash which is stopping your images from appearing.

What kind of cameras do you have?

Thanks!

**Comment by twrecked** [comment]
This was already fixed in [Pyaarlo](https://github.com/twrecked/pyaarlo):
- https://github.com/twrecked/pyaarlo/pull/35
- https://github.com/twrecked/pyaarlo/pull/36

So I merged the changes across.

I'll release a beta.2 shortly which will fix your issue.

**Comment by giffordj** [comment]
We have the Original Arlo Wireless Camera.

**Comment by twrecked** [comment]
Did you give your Home Assistant Arlo account admin access?

**Comment by twrecked** [comment]
Can you try the latest build - 0.7.0.beta.2 - I fixed the crash with changes in pull #298

**Comment by giffordj** [comment]
The displaying works on the second dashboard, but the first dash board is still getting the same thing.

**Comment by twrecked** [comment]
Can you post a log again? I want to make sure all the crashes are stopped.

And can you post the config for a broken camera but inside three backticks - that way it will format correctly. See [here](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).

Thanks.

**Comment by giffordj** [comment]
I figured it out. It was a id10T error on my behalf.

**Comment by twrecked** [comment]
Excellent, glad it's working now.
