### ISSUE TITLE
Cant change to Schedule after upgrading to Arlo pro 3

### ISSUE THREAD

**Issue by Spiff1** [twrecked/hass-aarlo#336]
Hello again

I just upgraded my base station to Arlo 3 pro and I have issues with setting the schedule mode again. No problem to send disarm, arm or my custom armed mode but schedule don't work.

In the log file the name seems so have changed to from "schedule.1" to "Arm camera M-F 8-5" but if I use that mode name in the configuration.yaml Arlo change will change mode but to something unknown and not to the schedule mode.

2020-10-27 21:06:57 DEBUG (ArloBackgroundWorker) [pyaarlo] schedule.1<=S=>Arm camera M-F 8-5

Any tips?

**Comment by twrecked** [comment]
It should still be `schedule.1`. Can you send some debug from around when you try set the schedule?

**Comment by Spiff1** [comment]
This is whats in the log file

```
2020-10-28 21:16:28 DEBUG (ArloBackgroundWorker) [pyaarlo] pinging Stamberga
2020-10-28 21:16:28 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A0E2057LA0F74/connectionState=available
2020-10-28 21:17:13 DEBUG (SyncWorker_32) [custom_components.aarlo.alarm_control_panel] Stamberga set mode to schedule.1
2020-10-28 21:17:13 WARNING (SyncWorker_32) [pyaarlo] Stamberga: mode schedule.1 is unrecognised
```

**Comment by twrecked** [comment]
Can you paste the lines around the `=S=` output. 

```
2020-10-30 08:08:13 DEBUG (ArloBackgroundWorker) [pyaarlo] schedule.1<=S=>Arm light 7days 6pm-6am
2020-10-30 08:08:13 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/XXXXXXXXXX/modeIdToName/schedule.1=Arm light 7days 6pm-6am
2020-10-30 08:08:13 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/XXXXXXXXXX/modeNameToId/arm light 7days 6pm-6am=schedule.1
2020-10-30 08:08:13 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/XXXXXXXXXX/modeIsSchedule/arm light 7days 6pm-6am=True
```

**Comment by Spiff1** [comment]
Will this be enough?

```
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] mode3<=M=>Endast baksidor
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A0E2057LA0F74/modeIdToName/mode3=Endast baksidor
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A0E2057LA0F74/modeNameToId/endast baksidor=mode3
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A0E2057LA0F74/modeIsSchedule/endast baksidor=False
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] schedule.1<=S=>Arm camera M-F 8-5
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A0E2057LA0F74/modeIdToName/schedule.1=Arm camera M-F 8-5
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A0E2057LA0F74/modeNameToId/arm camera m-f 8-5=schedule.1
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A0E2057LA0F74/modeIsSchedule/arm camera m-f 8-5=True
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] Stamberga schedule cleared 
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A0E2057LA0F74/activeSchedule=None
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] Stamberga mode change mode0
2020-11-01 18:39:10 DEBUG (ArloBackgroundWorker) [pyaarlo] set:ArloBase/A0E2057LA0F74/activeMode=disarmed 
```

**Comment by Spiff1** [comment]
Have you had any time to check why this is not working? :)

**Comment by twrecked** [comment]
I'm seeing the same issue here. I'll take a look.

**Comment by twrecked** [comment]
Should be fixed by pr #345 and in build 0.7.0.beta.7.

**Comment by Spiff1** [comment]
I have updated to 0.7.0.beta.7 but the issue still remains.

When triggering the event to change to schedule, in the Arlo web page I can see how the mode diapers on the mode page under My Devices to the left where it says what mode is activated. Other modes works fine and changes the text as untended

**Comment by twrecked** [comment]
Can you post some debug? Mine is changing great (as always...)

**Comment by Spiff1** [comment]
I have attached the complete log file, I start to believe I'm missing something obvious. 

[home-assistant.log](https://github.com/twrecked/hass-aarlo/files/5578262/home-assistant.log)

**Comment by twrecked** [comment]
Thanks. I think I'm doing the schedule wrong.

**Comment by twrecked** [comment]
Should be fixed by PR #356 and #357. It's in release 0.7.0.1

**Comment by Spiff1** [comment]
Thanks man, it is working fine now with the new update 

I really appreciate your help.

**Comment by twrecked** [comment]
No worries. I broke it trying to make it better...
