### ISSUE TITLE
2fa issues and configuration issues

### ISSUE THREAD

**Issue by ste19m** [twrecked/hass-aarlo#600]
For some reason all of a sudden cameras are unavailable again.
![7A1364FD-28C6-4303-8915-A430E4320C7F](https://user-images.githubusercontent.com/68481035/168468131-693a6fd3-f3e3-48e4-b3a4-fec6a9a3b4af.png)

**Comment by twrecked** [comment]
As before, can you post the debug.

**Comment by ste19m** [comment]
For some reason this time I add the debug and the configuration is wrong apparently 

Kind Regards,
Steve Challinor

**Comment by ste19m** [comment]
try this?
[aarlo debug.txt](https://github.com/twrecked/hass-aarlo/files/8695551/aarlo.debug.txt)

**Comment by wierts** [comment]
I am experiancing the same issues

**Comment by yuckypants** [comment]
As am I. Issue also started 3 days ago.

**Comment by twrecked** [comment]
@ste19m thanks. but there was nothing in that debug

Can somebody post some debug? Unfortunately, It's working great for me here.

**Comment by yuckypants** [comment]
[aarlo_debug.txt](https://github.com/twrecked/hass-aarlo/files/8718649/aarlo_debug.txt)

@twrecked, the log is super big because I have all logs enabled for the aarlo component and pulled all of the pyaarlo and aarlo entries out of the home-assistant.log.

**Comment by ste19m** [comment]
thought id add a new log see if it helps?
    On Wednesday, 18 May 2022, 18:36:49 BST, yuckypants ***@***.***> wrote:  
 
 


aarlo_debug.txt

@twrecked, the log is super big because I have all logs enabled for the aarlo component and pulled all of the pyaarlo and aarlo entries out of the home-assistant.log.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  
-----BEGIN PYAARLO DUMP-----
gAN9cQAoWAEAAABrcQFCAAEAAIrihPtXrMc2jmuraLPKjOfSuY++gft9B5hGookNqGnkJT2Fio0e
iFeZhW/njdmmq01gyHncWL9VmC4vdbAmJLfp87XwZ1s9Gbq/OyjD7pPxqdSfe9eY9oD7aGj5Wsjr
wDOCxIqnijGM09QzmsLF9B8wiapXwO2gkPBsovCJokLszxOtkXF2Ms0ZqjI1Gmkk097HYIX25duD
k52XN19Gok5A6uif6/PvefdVA5TWZfNf5ezGLRLaSns1ogw/luDmPGDhGINBDXFPXgymRFwJnz0c
KHrPQgqqwQ8Vcb07xGI9X05NkGadN6FpfTNixjUcuJxMm+NfHXf/TuV0vw1rbgxxAlgBAAAAbnED
QxDXkJeLxPakfnJGRdSYUFh4cQRYAQAAAG9xBULAMAAAJiMS+FITrY7g2IeBUUQFA6858idrUZoY
vGzxVUjAAtg+EF/6NM0Il9Q479YnCTE7yj/k6dXIRtbEZXVNA4HF9Rjcuu/y65ntkOmG0TCEMz9S
XGZuiURYVAMdCe6ktwp8VFvTxO1srQHkdlQ8XnjFnuteBg2OY7Rw4SBgJVeHi4Ff39e9bNjLFVBM
IzHLAg7Q1d+AMgBzAM5dHl35b/7GusUOf2ELGOIXl9Nlr85zzUa9/Mh662KiPRd1m+bCId+fv64E
LdfIZ5fNQRjlt7R+Z7KyylMoUDcwYZG0NATFvL26Qfy1hAcNB5x3vl+c7pzqvPEnJpArUfvEM2Gz
DufPlXRgsee1REx7aHoM6tOYGRh6FLki7bw9pkNNP2hfjI8DXn1dcxrdkS1/fUbUMhMIp7GRP11X
l50WR4XeRkc6ETQeJrp/788y9cJ9cBrx4MfKDs+zhtC+EJcfRYzeT2UT1u96yXt6kGv/h1/AvEcl
x/7+9KqVQrQLVnFgz1QwzRuB/9ncDi9gz5Mz1cL2du5fJHlI8EojWhc39V1TFKugigjCuY7wBV6S
K4jD3k2wSDwwPgRMYQdkRYMayujW7hN9BzNyEI7fcmCiG7MndCUwVF2p/769uiyQmDYYqK57lAtV
XYOxLzoBK0xoZBkcAi7bzll9K5a81GuQ/lbHzjSym677EY3PyqghsHiqXmkyZc7aP5EN6UGH4xGE
eE2KONMwTuRZbIP/FQ0cG5QIwHwCEOn+tRYRdFALZ0a9ipnZotHAUWfIXP06Y/s7/1Xwn897Rd2a
MHE7JmQazQC0uLXXL4qKeK1jpP+BhkYAAldJZwoulW5dyFakHZStNU4Hg/7UKe0F3i81pIxEqPMY
3hb5KLUpTMdDMdd0iJE9oE7Kzy8ecyGxa1bTeVfq00FhU0wBcaL85sIRTFdQ3yBki7e9B4ApMHDH
2LiQcWov3V1ryb+G7W39FKnwmH6lHz0UOTSZmp9re5R9GlbvGpQIlYtIb+H9LiTCMujfInUGp4ZN
EUbDu4WNafQ4/YqATFW050A9i1JSa/crGs2HILzpfBkHg0RBemyCa/imuj4S9N9MAZLDUc0a04Wi
353W0lpf1ue7VtK1KAwNNi/N4cXsF5c17DqUDOaVkBl2NiATwPlAVnV3tW3WhPZ32CPt8bN3VOBa
++df7ai33YAdP+t4bTkHu1XIgQenduHl94tK16uedrR8N5fFklPdo2tE/PHXbyxNU5qqUuR8hEYm
jcr5IjPtf0UmpmYU4jQ3Zkt+YbFrfqlZ3Ze9yM2UbTBb8tKZ62zsBZhnKSSpEjRlfHfKmtv1ZLpO
4ovEKn4CgBmVLUJ3chxIA9o4dVoOic1jbDB7lGHO0S33GFApNXQfs/iNxGX/eubTssrGvhJ1xza3
7uK7FBim/AKdlkcmN9QJxI3zUx5der7BfPIt8tCHkFuvLCBbr8xhC4L5S1A7W7uNwFcLx+t3X4eU
gHVHn5BrnfYqRMME6Offq7z50V6UhPOZGYeeLwH9u635B8SSVy6caVi9MhHSrtAU2m/yz4BqG0YU
tHQ+fHOS2MorurPOSIv3KRpA4lhpx702Rhpo9iSGdmjbnxsIEXu06LbVDDnL0IBwzTNWvgrJDRO4
0LNmfwZvhCf9+bX1AQHTkuNHKtYFIg8hzrOKSD68wEfIk0DQxiMU95zD7Fzs86/RJPaUkU02jbLX
ZhIwwk4Db5guOusMq33DAT+8IKt2RnK93rA1w2y49PW3G4Qit9k/FpNozaGH1djmMQg2ivBdqrVl
PZgzTODYcVcMq/b/13CSarxUyYxAn9Z/UR5T6D8MSCYEN1wOvWlbQRGhONbNzG928aiJy/Kc0xVl
bHNg4AdhLZuyx4juGhzdje7/xno6J5BPziQvLomIqKifjCOAdVr6XpMLFsi5Ied5cQMQ5VxSd7v1
6DhbbzCdIQxWDcMB2Trl0b07lWOqcvBu2LezIf8H83gNgxtLH1edZfSHQjE8it+p42jDCHzdNiZN
dEc3YEPHGoJUcRX3yfcMor29qaHlK6mQ/3gA+iK96eRrDB0hFbP0P7BmUMeTHTr8k3pBfsnSXNJq
yvobtYi4DOTBYiCAN7yOm9VKlGy6SphrbQzxVpyewXQVy8cciX7SnVPxTCf3t3HrrAXuOw/VR237
KW+FEEQCQdk20zo7AdGgtOsDQuSsgdkLBPl/YP+xXdzFn9Cj/dgiYmByvWnpbGQVf0F0mUx45xpB
MPdgeYJll6aUjPDT7YMT9okP2gXQYYQzOxQV8YTKAQEXB6UeatsTpQQvPXM5Abx0xv9YuIsJP5iY
fxjry3b1KiycbMI+EKBkWVFbzpccpNZ1mLzpH9tcn6CrjwOdn4Z/tPHePEebqQYqGi/2Od+Z+beg
ny5x12lmVKxv90IZNvIZvzqASE55WlEcetuh6VBK9KPJ/k8nL1W3xN4SV7zhp1Mc02skb30VsZuu
s3CB9n0UX0NOmh3ZBPLxUgfcgtAyq1rAOB3sPYNhnFhX9rPhCErHpDZvUIccqGH/yVKeb1fowfa3
wrW8qeK4suMI01mamyonLHeO1XYH6IdnHNdb0Ha0xDsqljFeTXIO+QLQdvhkc5INu8sbMQbLdYsC
tYi+z3UAtzR6lh/DOJpFQmRPW4dflIPCIPWpfxDXc0/a/IDPQOYz4GUwRxaQelAEN4pjdjwLLEPc
8LHOz9lXx1cpg6jiYvgQkSBSlFui0VKYD8AlUDfQNzOwUk81tte1Spo4MVz4qDU5NL7PDOYFuSez
uEXHafRWXXvHQV8mXoM/lttQAYZYMeAgB8sjLwS7alO4o0VgrWIyxvA5ZMhx2MC4CRtY64P3SEb8
wl5WwxX19jTD3EaQ5GxNRCDaiuEgDYiIGQdzIF6CmAwigk1omQaqDVhqzQBiCK+r5FFMkeCfBwIl
2gclaEOVenjoo4ArJUUVHSpOKmYuyRqXXsq9jZobGYFrggRoU5mPqmc9MBJ1fGQBW4CBu/OOnA4l
J/MCRFU0NRUGtbilsHpZjobNQLOWgAgQbBRlaBGaRX0vTt/kCFDpLzyGjHS8x9L4gMSqZhoq4pwj
yRz4M4+ECFGT/+Q7f2viOUCIrXsuWSPeLTKbOjYjOVxTygFR7nCD7uv39mToIBIWq8ILXsV001sN
MdccHzVYJsXdJkLOlvykdqY0LImELKeWXpyfv/gHGmNhghWb1GPjo+N+zf5CSOJh+aX1zJto1Gn+
9WmR3ee2eycpRxdeQxdT1N/ZIv0OqWHCoLidlCja1Ef4CUhrOGKty0wd1ly5f+FFEeuW9cf1/JUa
/9e78E3cmd68hmtasLs2zUc7WsYllQ8AitEu7nypICQKOhWqcMEsCVOf3qmkcmI9i2lrWcQRwvV3
lJANXoVSiJcJTuYyc0sBqNN1WiMUYxPc/1BhBcVycBH/rlfNzuqeAnbPJ6kC+EU5bxPH7RlS69SS
NViqwwYfUr264APeoiPooYR4MIrCwxy1ffzI5K5G1IsWxcMXlk4wERYcq4N8pVf/Y2ZAOpYP+kfw
ynKHLt80OAROojO1TvxkVLowYR5m8C0LnqWsSLknpC3RXa5oNMP/Y4oDQBlz81J8x7f0q6sTkqDF
3swSW3yw6ioUwufCwLvgfDqWykEU5aceSbtjMkP6KBoYqJhGB1hrxunrZFbEw9bwJtQh0B9eICTx
NQldg1XiAbWH4EPumzXQ+D/WHtj9GCgxoeSC3RFqJs0zGteD/hBg7BKmHPB/AS6MsR51JD/Ttlvn
2nR4U/pku+4gMCWdURWnuTK05fxi/ntXYskIHki7b2BrtUYaBSnYoyDdiEEuRExSRCxbTtO6CR4U
zKmDjrsMj1vS6PfazpJzif9JU8JKD7Y4kns5L0X5AN0FjL2xP4i1rr+tU1VxgxaF1NJtY1UgQj2Z
Du3woHBB3T5DXvt2utB95VJtf2xgX/Kx8TJNfCMnke/5HH8ret0492JucTqxA/wCbOcvoB3IE20y
Ie9Yd2mHJLjnxsihQNdeJGD4BslHdq144pSWKzqvepBdLC4hSaga+4BUBgTwKnUdtXrUhe/GBDeK
VSFxH4/ODFRgYInfWNhk5qu43hvumEJclScBVbx0eP9LTmMmH+SKDibN77RLNp/sy0eqQL5Ujv6E
koKd5J93ZsdtxAdtsnc5m7Wm33lA2QRD6F4aqG+8q86rcHxMV1DTqXVd5EjiklaBEy/xopez1K4D
lK7mSOKu/E0HbIk3wD7ejRGZ/RhiTHG8IZQU/P7EOO5PGqg3ZdwMD0mugB3DW+//vs3XvxLIvWGq
93jeyBil3DvRhTWB4blabpKYZS5fC1gAztrJwktJNNFGfqqUdQmRVFldqke6XhJ47t1M590lce9W
jmmPYCMr+OnFEyikGkPExg/OOfSRB8pGLWsqXz7CBiAHjyE4URGA/GiCmEf07+JBiugCQEM8ZEBo
jzFhVMdHSSXbA78N3LdAaIO/FQipzTbppaHKdYycNj1EvnvczijrlNusMnr/hdFguhC7rHF2lh+/
7arqBJmpGbA66WTGX0ohoyoU7VfSDqgI32oXSgaaZ+CVAG/D3UuRyJTVHGSb4u5XhVtIvPlm5DRU
e6B9BDAI6ndLDpKOBWER3fo7WIzGZrefYyEgrTXsFX7COAeAsuvVl7L7UkfthN7KvBF+4w2zqToa
AGUNReu8bjRRKYiJqsL10u8qOhSQay23Xl1galXm3NQ4Gp/1QOz+5e6DmFZso7/B98lPtyGOVW3e
hLakbJpW/avCJO6wAVC3APZzpzsyM19UOAMgmAVOeU04MM8hQ1kCja1PjHJrneswlkjfJxBSUYUB
98p/8iBxa0MI31iHfbJWc/5wjWq7C9+CPu3GmX1nw9LmXCY17v8JV++Zidd5dWtgkPXpeIOvXLHX
FT4GHSEa4QkHjV/+vMbAMydY9n2MvhOuV7PjBpjpY62tXhYBKI6WuXRlGaLfAn6KsyOH06OYSyP5
esoiGLR6/0ZLa2Xfb72MCa3IxNTw82INnKLYfTXBCEtwdTlD2xzs5pEAB9a1SCZR9yYBT6Qx2JaB
YPdaZFATSZMTrWfamxNKcFCxZm5jEFBEf0DIkje2CWWGdbxiOgVCfWRxhXnXP6YtJSVSvv4Shv+O
EaOmyWJatDQUA/+zTAQhsBeC0Ei8bk+3Tkxu/s4dwx4BIJSmBAq2I3rmMAIfa4rRBJl4plHJhYc+
3VpCsQJdVILvAPae4ap00M24co4yaKEUcRGbccJAtzjs1qlo7MRtwWmZvFiFg3vI7Jfb9JqplKGP
QIcJXg7swQJ7iSetFdhkXRAsHwh0Cz82c0Ty2RO1lvOud2kb9sqbtl8bK9AVoooWhTB2GdQ3wO98
WNbCJLln8KYqBKvad673Yftrxogs3bB3ck95ogxGbJfkiYsXQICxVaAiv1UzP1+Pj1RiqgON/3dr
gLVSwunrCmFUAhABeREyV8zCKrHn9B7TuyKykJLe0pSgGxDr9+z1sksXE1i0xLYJRAICzoYqHpAi
28F619S9Dn8P+5929S5iMx/GZ7b6xIMHA3JcUoPCMakSEr+sSqljyMEyszWdTUOGKA7YQ85/quBX
UzfyngYJKmY6MpTLhUui8S8+y8pxmS+nnV0JmDiEx0CfCyoajyeEkE26sJraPDX4KYm84HbLPIEM
pWtGnxTczYBX3QIFb6h2Ny8T3DjcJk+JIpH1u6ThmhVKMc2OuKQzyzIYVcMxOerpMNmW+zR6fef2
5KKd9sVxc54ivSDRr5/miN8eT9QZuSt6r+lP8Vkvcr5lelitkFytXeWxMjsjsfkg35qc/P1/WJnC
s3WJkEV0MvWQJlD4u8V4HtXF7BYwuwlrQtiQSeIuwgEa2ZcPiE1b9ujp1ZekRGmWwsyd2piiebDC
WywtIZYZLJRjohWywjYQzCZJvMxbb2Pxog/rkHlDw5lBFlCdUcbhif9mrE5udQWPIdQHNt7/C8L1
9qgqsSJ2oBbEir7+Gt3hqUX8eso/ts6HA4Ss9espIEA2a3/TG2NX7G/MvHIuqphmK6F4qAKZtTKM
6LBcXxpv897BTXHYY0CFj506Z8I8t0u3UvGlol1TSAjaNeuuVmavVJEzSnQi0W7gtVSpBRBmxAYM
jCyWuYfO702Ggn8zyGjT86960GWmowBhbK/Zf6cEtYz3x2IlmXvTaIvECqprttY626xm7bAPTz9y
kl9NnTwZHsq2+SYAdb2nvyu1i2Daijk/CvAfzyEnWuLDW/41wYlXjSczngbQdA3znODbutHoXsch
XYh8G0EgmRmqV/E79ZMSGU71zWkmkU1A2kVm/5fSEnceRRlU8w1zac6HkXyV8C/IHeP+oUOvwFk+
7fww0zc01brSchePOj6VaixmmNXXTh/rFcxlLv4vYyqaoXweVDqcX3WasLGEdkGJw+eypZE1FB/7
1ywmxrLq3R5GFdb/gcjbg9PM/7yh60sLSAjXHUCYLdjU/R3rpF/3PWsAdr7lhy1PN0tIKHkyu/FI
u5CmyeQBV3A0YdW+dGSnGpZF1Dvh5aO8ajPI5/lkBVX+79Nx3HIAwrvPtZibhXOMA0CKGu8UYHTo
mh43MER7P+wr5k3yyOFaWKZdEmyBt8KA0UaMijDxlaSHY9hgQ1Z9vo293fdjSxJ9SyK5Il+89AvC
/pdK2QP6YuSUNHpYg9Itzy54nVgyzpcB3awoF7yJdEDwuqsDtDu3Zsx4h0EPyEi1Bg9g/cTrIRyM
TCTJEqfgx1J2dU/FiHpnKBkr69fBvt2I7uWIR/EJpgM/ntCYZUNvycnHsZARpMIrmqXH4nBp2bFx
eW63ipKU9aN5gpvws4xQU5jhoaPoH3fALTyy6qRF3HeIgySmBGOnm1BRKJ7SIzNz/x4KUNvHPbFb
8pFP3BxmRCfSGXfW6s2VHxamNhPm7k7RWvBvQX6hlAH8zu3hzJEuVXVmW6kzFAaSYBwa53VO+pe1
RtOtiGuNcMLMI88yPH2DDUJlYTg4YDfZZ3i1ZbRqdzMG8ElKetiQLRJZkWsV7sqm1uO6C4TXuT3m
EuZVEN0UCNFJknfeKFyY8UVSzNqjbiDCZT2eaOadtomlq12pg49/bRM+dR5WwtN/5aNaXEjb1Dci
NsKrGi1ro7H1eCnLH3gRBx4r01bXo0uo9q+ND/ip+ZLV/pSVxU65+VWnEyXJ8vz5OsYiYpoEvKqJ
39ZVNbaC7oGBNnKhen77enEkTeOOmxHeLp3zc6YsM0yJopUjvdx1xn1VoIJ6Wctewn2zH55dLKIL
eSkLaC9L4QbJliTm5GWVtvvuPWDMRIqyzh12c6IkI/bJNwkqwnQI7Jn6evDMgPmYXbtZxBBEd0RX
EyBdL0UZ0X+I8Pc7FoqtANvAlbOpZm7U/fKAGGXNbhFqIr9GXbNTEqCpZmGNKrrbh9K7WgKBNhag
fSAxvGAgBGiiQqz6k9b8VFpT5R2fMpMp2n0AenBET3N8vhxTxPgFu9RRYiluGgvRbfqJhEQUJH19
/jwEL+/EqLQl/6Qs5qEowQ8kgmnhQvFfP1pgyMlN31ul3wGPGr2Fq4E/kmzSlm0Fcuo/YJn87Hsn
7ecHAFZP4vqk3P2O9sy326a264M+Dp2VHVdRVfVgLXFOa+8OTq1xVH/kZ+Y8ET8VmG3BGw1lUbK2
w2mh3DCwx5vu/EES28LcQzmvH0lliiHLGE653bjBHKvPo/4ziLsM9d3+DFi5kFROMtzlY7ltFBJD
R6uyBQuJbmfFm2TOY6U+CWur38kU5f8qAtbPpBW7xCPoQcEULSudMrZGXyykGAvHiky17cembQys
T5AYp0wjINOvGNyriqFA78kSAIpeL6XpD6uMO5TiVfVUPBSsIiiQVTvN91xGcgS2DqlGVssbhfru
EbShcwQ9OogjpeJwgZE6uznhwgOOWQRqSUhScvGFikczVDvUX6GSfUHskv7vM8U6ReevF4h/wwoR
8TaQMGCa+jhOe3EK65whE2QR1P6U2az2v7mhv4yDO35KRvmOrAbWYWP8KQ1k+YCw48WepUq1oti1
UQoaoWJWFqwy11I4tus/yTrgwVUwbTEmYKxtNZaDhP2xdTyi0bM7AsBHPdNMNbtvn3yh9bK/9n/j
wZCFtcOlhU6cUhzv2Z9jd7Rkn0UQuKhA4qODSTkOVYltZSjDNYw1odd9hWnW2MPJYRfw5otsUSBh
DoQSxxW61ZyFcmjucut+985PjJC09xeJoSGEqQKp/eV3LVxsVvxl2uGXEE6kfT3y5OQC3n8KWkv2
eE3YRYUdbkp3Wxyzvt09YbepjL6KNGmxJ1g4VrM46obShUUGr114C3vq+hWFn0lVurVqD0y9bS7H
rkzU/xXBWzcQ+4VKUYjnbKzzjgW75iI7/Px+WcLRtr4z4maOF8xwow9Fa+dB9suDT3LmaO9WKMbK
PKJUVcy1GoR6zU8J/la3i/oiskV68hmPcKZxpYs53vxdllGZWTH//9bhUb+5/hFv2X1KD3fh6+W7
7ID2TsgGEfxoUePGvPNZYnLM2JUlOMGx0E6i5Ao9FeU1QkpwLHIVwKOLPu7IBOy1RyulxU9U6Ya/
osV6hGVyOyT5LxF50K89lKc37FpkHoXS0YyjeqJnc9e12sxjGZ7YZecN0JA70B48l5Q4g81EGmBf
p6gWDI18tyPlveTmYjeDXUUUGvZe+7G8q+EhLBhcJJVh0G9m476U+jS3DxAQR3QVQtn4YW94r3jM
ytuc8dWjImAf3MUs7yMifMiiFr6ewI/V2nYSUzLbb3Uahlom5x7zgjUERTDBjRoo92c4b8F2xaBx
4RgmxxztW+Dv+tXRuOHshzHuMzknZvlBG9JMt1eg6K6t47lpQvX9Flp66lJuSaVu0eekXuoaa9ob
akvsY8Wap5vqbO68iOx4hS3lWwOH0IEqcsORRvOYYVilTuNIau6oPsqzfn7rR0PCjMIQ8mHWIkF4
X2LiJMqFy/VQ0rvwtp96kU/9TkVRBxQacM+eOe9IMh/9/KL7dfiL+iwmkHqned3dUBasJKD28i1z
ef0xCB9sSyor5OlVocAy+MhAU+6TyQde6PTNG4tHGCuuD7UxV59h0dG+FbRzMPTHgBiwRX84Pvjs
nSS6INSHEPIE/UJG0wZq4QPO7PliTreEgcU2UW0apWHIDEqSzxKn6bGm515WtLZoU0OXtsoljD6a
OZDhHpbI38jClp24UN39P9KZTQ8+g2k7w8xAc4rs+cirsShG/7h9AxlDn79ffPzvRYKulMrFQFIt
YXzgXSpJ93nKqSKfHpAPige2gLRJlOr0DD3OQVf+kv+GWDHgXnM+ET96PUeoQRM50FqNlRBHsdus
2UHxh+i+QkCKKNhafZgiqtxRduvMSAxuulnk+iszr3WAaDBQxVx47sz40zVWwyG2g21ouauUTR8U
nMr246kSdy/Wp8W7h/OeONvBLdY/L916RCNucM6F/sxOjHSM6ZfUrcMk3T5l53KqQvqPahGzl/bx
6HggLhRrOrbkwPYteh3pTusD53mEEUxNPpOhoEkhxmpHBsvbCNcO8igv8vFuYrHXXTkNXf+Bgo8G
sAe+ovH+JZr7bHThYEPEA5kzCVmZLuLABVLnfrUk8skV4FlidOJjZGhjmA48IRvkLXRFYW1y71Uc
cLejVvBGjp8b4xsfU1oaolcaA6Ve8NE6VcBxmDCLh0N4WUAyUhb6gHSFaAq/mK0yqQPVZuO603CY
oqOvfn+OldAzW4mxuwyhhzdyOXvSvninYNABoHTdx7fNkOF8KfjjleY/jbTURYAS1MRfGEcoJZqS
mJuQHN9IfNSyzG3j8bAm8JgNoTZVDVGQXCgEO33mOy1ziRAPr44lAq3ISPEQVWHwr9M70RQcNwQ0
5yAAM1Td+/VKQJ7H5yl7lZ65tH0DRAMfceHVah/ijjMNvHQRh79PJvWNg1Oduup/tN/6zHxmZbW3
XYv6gadeWHNIVzU6B46hBvzJPTsZBTLenZXB0V+aH/+ii+kFIiFgMnUEWj5DItPUWtvmVHP970NW
iT4c1WUrKIfGDWVBftg9hdexUoFqtaHpwbehqtusXYxAu7kNq2w/W3X9ZQVWZw6LxZaGP3aNgOAB
LYgCNH9kDeZ/mpC2m1JXj1yXgvWccRzpjMQdzfQakiQ8RFPsOsbQWS34mOmvFYewqXPGWB3ner4O
tIBm4sRmsXigIdnqL66nAf8GTsg6vXMPLxl4mTytOhW69rFsX1kNoLBjBN/1VZrUekBerWFVYC0N
hFpQ8Cdfmbt4Li/XTbrI1nnQIuMNKrnodhafGaM+/FztsrnuXIjzrs8YUGgHKFpcBqDx/KB9DJxK
WnZjYusPxDpv7gACxuRPsi6FfN2pXZgYFSEUNvAZHaXJ7w0qXATIdj9u5I4900PZ5ZYL6HEK2HJN
YDGv7rm9AEl7BzOnxsxEc5791hORtYWSiRh4Z6kdw7wONf5DZ6cdyjXFZ6+QCIvbU9q+01kcAE/C
rV6c1/LyORZLVj8/BAvez1hpgXEnR7Hclae9oJI1dMGeEUNdjasHbPIh2Rxghpw0pewroJDErQ5a
HqjR2M9XZHZ4WKCGYAEuaL+fZFyKEsHxPM9nbRAUG3y3cYyRdpxNV9ky1SRxjW+9KmeB63/qEY8Z
qKfchypskRoA2uifYPYN0N0wFZ1XOeopDCdg4bObiScEDPSOd7SEFD+fkfJhKBnJ6qZCL3Q7G4NS
rDVR9//QNuAkuto68oAxSaNbaKeUZlSmY6ICjy6BVfy6b5YvVbBrAINIbqdJTA3XUvilXtHwF3Qs
WWrKQKO3tJmTNjAPJ7L+nzy6FFuqv+AenDsZL4i0A+FyI5BxdX0o2aVpwxdcrOp/DCyZ2fdYVGpU
FAbPnrlEJ6xTxBv32eX8tAaeHi2jD1JrFcI3ugAsz05jnMWNkwhVlM0sDVGmHvo87JHSifCKnN2H
J8sWluprJoDmH/1bXbOnfgiBFTVTYpL+NrHO2BvTMvgEszJQZZqefKEgFAOOuDpENA7sL0+RH7A3
iRaIr6ZX2F1+TPywVgzycQiQjQFBxcSOug1Zjm6KpRx1rTlykaregWtDdDnek1ee7Gq0CCVKN/nR
3qbz1cyAdnOsnLfOTJS1ZmkQALF7PDiN7NQBGiMGSCzGW4AK3argJG4gUYUUUpnUoEH9F/3F//8I
+opEkw/8aag/DY3QfP/1Mkf5E9+4jF85yL/vmoi3MBXYweAFz7vn4iRD+yAlPHuwgpxWTt777KUq
DMpfj/QIYeUXVyJFoRBszvwTJYXZ/j6nfUIkPaHYXZGW4rX9evOp4hPXfi/p+OfAUCnCBKbId7xB
/TVsbd6FH4OLj4JqKvHkhefAdwHsyRf5713vRYtiS8swcWFeQ8RXk/v6Iud4FpKDJ7JClM3j+3aJ
Q13RMigCaUykMtkhVrShEXzHCAQXEIXA6n3Q8VZ2F372qQAZReeLRRmwUtCMkmSberurHC7WqH5Y
0GZvKP7E5X7qGntP7lFvsJxRz0RoQe1RJECnZU0V4zpSzXb5vNbOvq5gxJdrxmjNAnkDgZpealOj
WaqyoyYAoPogynlsHkpIbbgZDT6Q4PxJALDtiBBfIrvK9IRgddbSs4xsW3ArowN+PKYJvQDIznAl
whUlim7HrTQHH13b/jlMY/pZMaFCSuBd0mCoAHHvxQrXQz8952kyy1oNBOetTc38YGj7UruLGS9W
/vBAWBQlxfxFpozOXG26GvaNdNYRw4oFxeIfZ3CJqUP2NjPbW+YWgmj26J6OdG4bHZpTFF/qzsKO
6KcG59oRzBrRWGJ+dPdqYQVHpqJHVOkbFbECVyghp33KNqNsSe06BwprKxsGzQuhHazSa7SaS5j6
AWuXH5felREEfoG3TQgjEUD4rDEObRMbJonOgx6jUoYeegbQWptZZ0FgwvMBDpNO1EC+m6Hea8al
MQr31usLAjkaMcvAjRFGNSfW+N59Y8txrFSoGl6roLa1j1KC+ETwN89Ok/70EHciT4DqPnccyCQY
k5+upAuZPeGYHsovhiL/bHO16K/YHiJB3P5k1BaRdOHtLNV8MSe2pJBsOOcadl/yWX0wNvNby8wR
/Q86o+HTlog6xC7xQUlO3DvnRSXcuu27JGZ4cN0HQEI4WHX/pJYuqt6CFSibABNQ3/b8gxI+7hZ8
ao188VTTMvDGgpV3kGIf2ecq+gOJY5FmvAwQ112aqqaPHAaDIIRV8cw9UXuZOq26OmiA6RqPQMj8
7E/T39I/Oii1ZL0yM62/U+iSas72cp8/1CHK8inlM3clWZqpSKWy4Xlxh4tMeJ4Ytvp64lJ7W6vE
ruRRRwO1YWsNoJaxtY7uzzhjclsybp/DKTTVjZtWr4wSkQne2V0sbTVkSscjhw1QyOfwC1JM4D8z
gTjIOuMFtaEh0mTvqAeo5LDdXGZuYwqZfJ4vEfE+dxJ3wUeKjSiEvWuw1cp1QQ6Zm79Vndk8Dr1Z
HoEXVQU+EvRWwVcBb0rgNNwR4Whu4rKyh8xGRKcj0InwiplCMMeKMNzq37UuLdBG+aPYThdNc8Rq
xijeEWJQGecXHssy8Bjo5NND9iRwD30Ijhd8P5Rfc7hvbJm7La2qs8ug1OQxWaEVaHqdZ6No3ddh
DATzDuKev31gNgOCR9Oy65Yj36qY9NLPOkRdVpL7dH7vpzkgzPtGDYW1boXrdcF9lbYRTU7TTAYY
c52m6C/5kiVzRz1OOjR5sUdv/X+AxQc8tmqbzGXsFWZ0H0zT+hmsLyvR2BcObdzM7epl4KGP6+Lw
/tc4pL9FTWX8HmK64kMAiRgLdnp2y2bIk+cqAY01QMu+Cls12GGA4mFWeV1yGdXi2G/L9n6Jvypw
Zon2hkpF9ALKShIkL7J7xLOr3FoM63zjZd48Jd7cgxJEAWAZe71Fl5JMa1unhUj5GjxoZxqQb7BW
Um0DYSab14+NKvn0d/nuR+GW5BGQ/ShY1th4zCfbELoPlooQFEOUCuAr9BBvhoZbqe75iEvWNdx3
HxslulGaUTkba1XKmWEGJYOZoPhT+qElZGKh5fm3ElVYeb1hxW5YAnIpDVElFmPMm+RLzwiw3GEB
+fL7OlMilnCxC84mMDqRLm5VLlF2rl/QR+bk7+FHMUI8x8OwDfxseMomVYp6wquj2mDfwEHj4CuI
sCVcKsCMfn0Jg1QR5JgvyeCwtcyfHWRYfif0mC2AziJzK3qc8yuIqdlMU0zwEpKhoo9SwFYPmXJ7
tZ6pG0fW8vNPlE7Fu5ta22AHj4K7x5Rn6E+kYKR8tg7tcqxuW/cmmurvYgOnS09UPDqa9O3Ubr4f
hUrDh2pp3MN6eMgnXNsZwCRrDaOXzUiBmQSR+F/upArOi9HOGkZJdXeB0y3kLQEwTwXBLFNQ/Ahj
CNwX529wEp6u8XAXdKt2iLpIKM4X79UzQ8kl/AMjvyOz1/AFd1SlyokdPsVb9y/WAGRr7KOritjk
CsdjK6gK0/w231u0tvn0B45SIR5JJw2bt1fMw1DQQIW7vbh+0uZNyD5kTW8xQ194mJVT4n6iyoSw
YhCdbdLrjLwkaUv00PsqMt57RzI6FrYuBxcPRuhtJYJ1WRnvflq/xg5yaAUpQsIxydFScb6b7M+m
y5c3iG7q6+a6uQSuTRPRM2dA+PrdUmz9i25cnq9Ie85sI8b9qfQOdHer0XbDhs4xyB1TQ5eOqdAe
jxMGTdPqg6rXailTJlWFYDJrivPtEVgnA0TRvb2MfMB95wNnrcj94+Se4kZ8wr42QIj2mf8BZ6hB
fsL4hXox6qO0Vo1gsbZ4wcy4lxQ4298u9i/1KL1hYwEvVx/UQfVit5M6ilV0MgXDv83iWt4OfU3Z
q2WT9X6ld9qc2pg9UBE+nhg+U/DMZADWzRVbSCqqdt6pW0jI0ySZOExrko8cjbeMaj6Hjn/qBbUj
xp55DJaOQ5c1DTnoOcDgDd+fSCsRK8XTfsi2o9rktN0KyE02HSC2Hi/dTcU3pALyIOc1VHvAGUcG
QTU0XPcVguFnEF+afqBcnPsvVOeZaRWQiAXGJMWcDx1sFgPiLpXABKUygy9NTyBTpXLkPpbXRigG
++e2AMdS01eQbdAfj6mKD1fxZ2rIeVJ9Veb+O59nSiER4QoSWtL+VmZhTfSgG9VCpANOCz+FhSi1
n+Osfc7sq4okn4Y3Ex06TVYS8XE3GcOnH7th0ltspdyVzhbYCU9sPVsmzTmimAKYIxKQyNxfGLuV
uomldsz6eEjYWmsMky5J/CwxPRmVbkdMdgYQTkawUYstw5P4G0hn4q0b3b+t8JUt4DPgO8cFmHRQ
ZWZYRC5h4AC8vkDct0+RKziwEQUtxaYMY63mDO3CSeOCBOjYyRzD5GoCWSwz2OPGug6D0SUu8OGs
nMNA7YBZ9DSGrmQEUST7rpigtmTspIIsK/OWYf0XjwVO6nZEx/Lphjl4y2wt5Lzn01LD0ikW2v7D
ToMYaHgnsxPhGLQ6y3KbpPVmWMHYGIMS58WHJIbpYsy1YOvoXSQlWlToEUuwmpx4n1KqGhREs8fs
ded/GRZb7eILYRCV0AdOP8M3M8E4dv0NfaziqmsvDsFTO33wqnotXbl2CMImOpA4f0nLFBe0KiMW
TatFhiv7NqcZIc2N93KZNjjwCo0Ws3POo4ctEUO3IWhCmJMGOa7egaqc/fLzYIWmkmrMA3yXE/H0
UwsIZpVm4zDJH4XVWrvTycI2GOgfnSe4rCuYiIspu4ikz4UI7vsPOYk4Ehriw5HBLn0cI9s3GT9j
j7/fNJGToa61JF2/AbZGwAPQT+Oz61+ulVB627sA1rxIxrO1o+XAsCfQr7/rWE/ZtP33idhuLQ8a
lngoMPn+zdB7kOOOevgOfxV8Z3coRwKN5ag2Aj+7jrYSmY97WTwneXT4lDlf4vOjsMEiGG+OZ7Oz
Qw1oG7W0+QfT8JtoB8onYIBiH8pu5on3klax5N/9EGYiuNd7sQQ3dZvHrPZaYBQ2zZ+xq+OVD8pB
v1714pmgiitprtL31ZxJYfn+SCVzgmLoL4FPWSWF2Tz9RwRQ7eZNgDBaJKN+KlmDBfhvkKAGoYyR
rbLIsB3vOqOvNGabcC8LaqySXyc75PvfdQRR6E4t60wOf2yCWxIV4+bd7/x/qKkHmcTSPFuqtk65
8U2YLCQuZjRxycY62q4oY3MdkRzdEjNvYO/Hw57g8ueeCJAsM7rut71d8WoeTlm+gt4IIqOJfbqz
pEsaOpZiLTC2voJRq6dAVeN4C3bwfkGvbblLRwBgqlsYYGTdk56TuLObLnyFHpLndolbrTLnyJ/2
K9BU0VlQgRcM/yt1a/dch66WJlqRyq4G+2v9MuhcFsJuKWPPR+zPF6ux2Rw9s9VMA16f4CXX8uaN
24s2mbkwLwAph0xfp2fzhWr3hTTtutvob/xjvWNJshd2l2byfy3bFeHxWi4332+FzrD95AoMUFMz
9oG5hKOdouau0aeBlyIPpeUfydUiy3I9xarTy0FP6QT+kRzJ8J4Z1NSNt+OHgGLrM8YcFTRMpEVn
OWpcOcOxeqcyRccLr/U+8CF1hdow3YVE9t7EgCesvBPxTfhkHUePHV5C3/8B8ALzW6lpW4EOdBLg
BFAdt+auhonfn62lq54PdMrt1RyO6k1Nn4xUUUdz4E7JtEHOAIG+chuIECEAOtSujToO0kRA6apE
Hm1u5/oEqbYkC5dHNcgBL4BRmt5pbnP+n10OOcr61CLBfDXcEjBfEGpS7wHqixUKPbcePhlmiBmz
J1oqfnO/RoIrF56mmJjy4Xshp8bip3TfFxF4TujPf0UuWzxqIA+EqAiQ8yMxGRlgzTNWm++T/l4e
lrS4uWL00Ta38P6Om/KL1XsFPsryb7T3tCkljFI3ZvEaCte4eVv62RTToJWan+v77EyYc+sRP0hm
B0MW7wKKH65BGiHJ+nS7feHpF0+S/eZAvH9sLjrtjueHi2AX4MtrIQe4Lc4RiTFfapvbJi2NlYYV
uiFiIl11+HVIJCid+2XXWzAnHYif5awGKJStSFXcZuAIbKY9RQ9uyzyjqo0sfuUqR0xeW6F8atwX
HVN9ulzbZv7Tfu74rdi2YMqZx8DHSfLZZZIuroq03+d3a52GnZo+9kRK8ZfgaJDtrEw4ZnTvzrbj
soU+sZU1neWB3Fym8ph1i+NI2ol9Hs6BZA1qptPMPKAnuUE4dGTCmrQc+6yc9VzU+4y2m/3xTozJ
Rgh3PPsf329duExPjXuh+M3p31nR3acc6Cmg5L+ARB0GyL8Mno6xzwID/qzAjA2NI8km2WrYcWlI
oZqnc8foT55369C/23O4UZHNumPLkqJZZ2jhewwfdeGc8Bn3U1xi9pA3N8GuYAjpzudg+vbRc3cF
AOm0DsLXcvUXykB3lq/0RX2FBImDphfAtcprklnm8apOLHQ6WDYERGSMwuI+7q2IWpS0yUnbe7Ot
GtgGLaLv7BprP4F8WqVblLcUflP9pGxaEucVAcikKMJM3GVAJBPEedWkf6WwIVHK21umrTGJhJsB
APqKOdib/1g48ovTtJyqyp3Z6081i3d1xbVJJeVtbaU8DGx2DaDp7hipSY0OAxpKQvDN0q24D+2H
cCYa9Yqkns8flXvTPp86s2WBUs/n+y8j1RkXorpBo879uu9U1PTQggrNPYGCjSVkFK7U0wl4k0Kg
Blmv3awl5y04GpQ+8s//G517ueTik6fqn340zMSScQZYAQAAAHRxB0MQtyQehf8NwbMzQyHS2t/P
xHEIdS4=
-----END PYAARLO DUMP-----

**Comment by robfgreenwood** [comment]
Hi - I've been having tremendous up and down issues with this integration over the past few weeks and been following these threads with interest.  I saw your previous comments and threads but haven't seemed to resolve the issues.  Anyhow the screens you're showing above are exactly the behaviour I've started getting, however I noticed that in my setup I had removed the host parameter from the config (must have seen a version without it), re-started and hey presto it's back.

aarlo:
  host: https://my.arlo.com
  username: !secret arlo_user
  password: !secret arlo_pass
  backend: sse  
  db_motion_time: 30
  db_ding_time: 10
  recent_time: 10
  last_format: '%d-%m %H:%M'
  refresh_devices_every: 3
  verbose_debug: True
  tfa_host: 'mail.myserver.com'
  tfa_username: !secret GV_USER
  tfa_password: !secret GV_PASS

I hope this helps - PS I changed to this because the SmartThings integration has so many issues as does HomeKit, Arlo's integration certainly is not the most robust.

**Comment by ste19m** [comment]
Thanks for that, 

It has got rid of the 2fa issue as mine was the same however it still won’t load anything and still getting all the other errors 

Kind Regards,
Steve Challinor

**Comment by twrecked** [comment]
@yuckypants you have the wrong username/password for your IMAP connection. Make sure your `tfa_*` setting are correct.

```
2022-05-16 07:57:59 DEBUG (SyncWorker_5) [pyaarlo] 2fa-imap: starting
2022-05-16 07:57:59 ERROR (SyncWorker_5) [pyaarlo] imap connection failedb'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'
2022-05-16 07:57:59 ERROR (SyncWorker_5) [pyaarlo] 2fa startup failed
```

@ste19m Can you upload another log?

**Comment by ste19m** [comment]
I’m out will do for you in a couple of hours but weird that I never changed anything this just started happening. Does Arlo integrate with anything well? I had issues when I used to have it on SmartThings 

Kind Regards,
Steve Challinor

**Comment by ste19m** [comment]
heres another log
[anotherlogfile.txt](https://github.com/twrecked/hass-aarlo/files/8748049/anotherlogfile.txt)

**Comment by twrecked** [comment]
You're seeing this:

```
2022-05-21 18:18:47 ERROR (SyncWorker_5) [pyaarlo] imap connection failed[Errno 110] Operation timed out
2022-05-21 18:18:47 ERROR (SyncWorker_5) [pyaarlo] 2fa startup failed
2022-05-21 18:18:47 DEBUG (SyncWorker_5) [pyaarlo] failed to log in
```

It looks like Home Assistant it's failing to connect to you IMAP server. Can you try pinging it?

But it should have recovered and tried again. I'll give it a try here.

**Comment by ste19m** [comment]
Sorry I’m a bit dopey what do I need to ping?

Kind Regards,
Steve Challinor

**Comment by twrecked** [comment]
Your imap host. The `tfa_host` value.

**Comment by ste19m** [comment]
sorry im still quite new to this and have tried to work out how to ping it and im having no success

**Comment by ste19m** [comment]
And I don’t know if this has any influence or not but my doorbell battery will go from 100% charged to flat now overnight and I’m having to keep charging it which I’ve never had to do before 

Kind Regards,
Steve Challinor

**Comment by ste19m** [comment]
I may of worked out why the above is happening, I’ve just had a massive amount of emails come through on my gmail account with one time login requests from arlo so something is happening now but it’s not actually logging in

Kind Regards,
Steve Challinor

**Comment by yuckypants** [comment]
For what it's worth, I tested the login outside of HA and it generated a 2fa code from Arlo. However, inside HA, no email is generated. Also, like others have indicated, nothing inside of my instance has changed. 

Lastly, I hesitated to say this previously, but since @ste19m said it, my HA instance has locked up twice this week. I know that many will say it's a dying SD card, but now that the doorbell has been immediately dying, I think it could possibly be related - or rather, could be a result of the issue.

**Comment by yuckypants** [comment]
@twrecked & @ste19m, I would like to provide an update that I think will help.

This morning, I spent more time on it and verified I could login using my creds outside of HA. Again, I received the arlo 2fa code in my email. I reviewed my 2fa app passwords in my config and found that i had a ' character at the end of the password. Not sure where this came from, so I generated a new app password, commented out the old password and added the new in the config. After a restart, I successfully connected. 

So, I'm not sure why this happened to a handful of us at/around the same time, but generating a new app password for me inside of gmail and then rebooting HA did solve the issue.

**Comment by ste19m** [comment]
Cheers for the update, it asks you what the app is called that’s accessing what did you put? Just so I’m the same?

Kind Regards,
Steve Challinor

**Comment by yuckypants** [comment]
@ste19m It's not really relevant, you can technically call it whatever you like - it's only for your identification, but I called it aarlo.

**Comment by ste19m** [comment]
I’ve tried absolutely everything I can now and it just won’t work for me 

Kind Regards,
Steve Challinor

**Comment by twrecked** [comment]
Sorry for the delay getting back but we had a storm come through here which downed a bunch of power lines. I'm still not sure when the power is due back on so it might be a day or two before I my main PC is back up and I can look at the code.

**Comment by ste19m** [comment]
No problem, hope the storm hasn’t caused you any damage other than outed power lines. Everyone else’s seems to be working now just mine so if you could stop me a message when your back up and running please I might not loose the plot then

Kind Regards,
Steve Challinor

**Comment by ste19m** [comment]
well finally ive got them all working again!!!!!
the only way i could get them to work was to completely wipe my configuration.yaml file and start a fresh and that seemed to do the trick

**Comment by robfgreenwood** [comment]
> well finally ive got them all working again!!!!!
> the only way i could get them to work was to completely wipe my configuration.yaml file and start a fresh and that seemed to do the trick

Hi Steve - that’s great, maybe a stupid question, when you say completely wiped the configuration.yaml what exactly did you do and what steps did you take?  Mine has stopped receiving and responding to events again so would like to test this possible solution. 

Thanks, Rob

**Comment by ste19m** [comment]
Hi rob,
So I went into my configuration.yaml file and deleted the whole config for aarlo ie cameras media etc and the 2fa and password entry. I then wrote in the main config ie platform user Id 2fa then restarted. Once I had found I was back with access into Arlo I added the camera, base station, media config 

Kind Regards,
Steve Challinor

**Comment by robfgreenwood** [comment]
> Hi rob, So I went into my configuration.yaml file and deleted the whole config for aarlo ie cameras media etc and the 2fa and password entry. I then wrote in the main config ie platform user Id 2fa then restarted. Once I had found I was back with access into Arlo I added the camera, base station, media config Kind Regards, Steve Challinor
> […](#)

Thanks Steve - testing this now, initially working, I can now go into the ARLO app, change the mode and it’s reflecting in HA immediately, fingers crossed!  Thanks

**Comment by ste19m** [comment]
I did find when i got it all back in ha again that it locked up my camera base station but a reboot solves that

Kind Regards,
Steve Challinor

**Comment by angrycatmeowmeow** [comment]
I'm getting similar issues here. No changes were made by me to any of my accounts. I'm not sure if Aarlo is having trouble logging into my gmail account or why it would just now be an issue.

`This error originated from a custom integration.

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:668
Integration: aarlo (documentation, issues)
First occurred: 12:08:23 (5 occurrences)
Last logged: 12:10:20

authentication failed
imap connection failedb'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'
2fa startup failed`

`This error originated from a custom integration.

Logger: custom_components.aarlo
Source: custom_components/aarlo/__init__.py:454
Integration: aarlo (documentation, issues)
First occurred: 12:08:23 (4 occurrences)
Last logged: 12:10:20

unable to connect to Arlo: attempt=1,sleep=15,error=authentication failed
unable to connect to Arlo: attempt=2,sleep=30,error=authentication failed
unable to connect to Arlo: attempt=3,sleep=60,error=authentication failed
unable to connect to Arlo: attempt=4,sleep=120,error=2fa startup failed`

**Comment by ste19m** [comment]
The rest of us seemed to of been able to delete the credentials in the configuration.yaml file and re write them from the beginning and was able to log back in. Arlo obviously doing something random

Kind Regards,
Steve Challinor

**Comment by twrecked** [comment]
Can you try deleting `.aarlo/session.pickle`, it's under the directory with your configuration in. If that works I'll make the deletion automatic after a number of failures.

**Comment by angrycatmeowmeow** [comment]
Ok I did that, still getting 2fa startup failed message. I'm looking at the Gmail account I'm using for Aarlo though and it looks like "less secure app access" is no longer available. Without an app password anymore it's going to try to use 2FA to log in to Gmail.

**Comment by angrycatmeowmeow** [comment]
Well it looks like Gmail turned off my app password. I had to re-do my gmail 2fa and recreate the aarlo app password. I think it's working now though. No more errors at the moment.

**Comment by ste19m** [comment]
Gmail did send out a notification saying less secure sign in would no longer be able to be used after a certain date, it now must be the date

Kind Regards,
Steve Challinor

**Comment by rainieryoung** [comment]
Yesterday I ran into the same issue described in the op and ste19m's https://github.com/twrecked/hass-aarlo/issues/600#issuecomment-1152968472 was enough for me to sort it out.  

I was using gmail with a "less secure" app password.  The solution was to 1) Enable 2fa on the gmail account itself (I hadn't done that for the dedicated account) 2) Create a "secure" app password that is only available if 2fa is enabled

My basic issue was I didn't fully realize gmail had an alternative app password to the 'less secure' one. Even now their documentation will lead you to the (now unavailable) 'less secure' option.  But the documentation does exist for the 'secure' version, and the catch is you need 2fa enabled on that account.  

I suspect a lot of this is because I created a new/dedicated gmail account and didn't end up with 2fa enabled.  If you do enable 2fa, then you can create an app password again (and now, the only way with gmail)

**Comment by adaminaus** [comment]
Had the same issue the App password fixed it, and yes logged into gmail and here is the less secure app emails waiting to be read.
Create a "secure" app password that is only available if 2fa is enabled
fixed the Password in HA to the new app password and working - simple fix thank you internet

**Comment by sdrapha** [comment]
> Yesterday I ran into the same issue described in the op and ste19m's [#600 (comment)](https://github.com/twrecked/hass-aarlo/issues/600#issuecomment-1152968472) was enough for me to sort it out.
> 
> I was using gmail with a "less secure" app password. The solution was to 1) Enable 2fa on the gmail account itself (I hadn't done that for the dedicated account) 2) Create a "secure" app password that is only available if 2fa is enabled
> 
> My basic issue was I didn't fully realize gmail had an alternative app password to the 'less secure' one. Even now their documentation will lead you to the (now unavailable) 'less secure' option. But the documentation does exist for the 'secure' version, and the catch is you need 2fa enabled on that account.
> 
> I suspect a lot of this is because I created a new/dedicated gmail account and didn't end up with 2fa enabled. If you do enable 2fa, then you can create an app password again (and now, the only way with gmail)

This post clearly explain my issue. It's only a shame I only found it after I spent lots of time troubleshooting until come to the same conclusion. I wish I read it sooner.

**The above explanation should be pinned to the top and also included in the README.md**


And here is the google warning about it.
![Screenshot_20220620-211817_Brave](https://user-images.githubusercontent.com/25059996/174696992-adc3fe2b-eecf-414e-bc96-c3c16cbc8f41.jpg)

**Comment by IanSMoyes** [comment]
I read through the comments here with interest. I'm just starting with both HA and Arlo. I have the same issue,

"Error: 2fa startup failed
If error persists you might need to change config and restart."

My configuration.yaml looks like this. Any assistance would be gratefully received.

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

device_tracker:
  - platform: ping
    hosts:
      bv9700_ping: XXX.XXX.XXX.20
      bv6800_ping: XXX.XXX.XXX.22

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  ip_ban_enabled: true
  login_attempts_threshold: 5

# Setup the Arlo doorbell integration for HA
aarlo:
  host: https://my.arlo.com
  username: ha.XXX@gmail.com
  password: XXX
  refresh_devices_every: 2
  stream_timeout: 120
#  db_motion_time: 30
#  db_ding_time: 10
#  recent_time: 10
  last_format: '%d-%m %H:%M'
#  verbose_debug: True
  tfa_source: imap
  tfa_type: email
  tfa_host: 'imap.gmail.com'
  tfa_username: ha.XXX@gmail.com
  tfa_password: Google_generated_app_password

camera:
  - platform: aarlo

light:
  - platform: aarlo

switch:
  - platform: aarlo
    siren: True
    all_sirens: True
    snapshot: True
    doorbell_silence: True
    siren_volume: 1
    siren_duration: 10

binary_sensor:
  - platform: aarlo
    monitored_conditions:
    - motion
    - sound
    - ding
#    - cry
    - connectivity

sensor:
  - platform: aarlo
    monitored_conditions:
    - total_cameras
    - last_capture
    - recent_activity
    - captured_today
    - battery_level
    - signal_strength
#    - temperature
#    - humidity
#    - air_quality

#############################################

  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: memory_use_percent
      - type: disk_use_percent
      - type: swap_use_percent

**Comment by twrecked** [comment]
Hi. Your config looks ok. Although you can use backticks to make it display better, for example:

````
```yaml
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
```
````

The main log might give you the real reason for the failure, it's called `homeassistant.log` and is in the same folder as your configuration.

You can turn on more debug using [these instructions](https://github.com/twrecked/hass-aarlo#enabling-and-examining-logs). 

If you can't see anything obvious you can encrypt the output using [these instructions](https://github.com/twrecked/hass-aarlo#bug-reports) and I'll take a look at the output.

**Comment by IanSMoyes** [comment]
Well, all of sudden, it’s started working. So, problem solved. :-) Thanks for your help though.

**Comment by 6iorgio** [comment]
Hi,
I am writing here because I also have a problem with 2FA but slightly different.
The application apparently connects correctly to the IMAP server with 2FA, in fact messages with the 2FA code show as read, but then it seems to fail to read the content of the email itself. I attach the log file containing the debug but I've changed my actual email with "myemail" because of security. 

The key message seem to be this one:
2022-08-15 16:32:52.557 ERROR (SyncWorker_2) [pyaarlo] imap message read failed'int' object has no attribute 'decode'

My configuration:
HA Host: Windows 10
HA Server: Virtual BOX Linux 2.6 /3.x/4.x (64-bit)

Thank you for help.

[PYAARLO.TXT](https://github.com/twrecked/hass-aarlo/files/9338145/PYAARLO.TXT)

**Comment by orandasoft** [comment]
> The key message seem to be this one: 2022-08-15 16:32:52.557 ERROR (SyncWorker_2) [pyaarlo] imap message read failed'int' object has no attribute 'decode'
> 
> 8/18/2022 UPDATE **SOLVED** I've created a new Arlo account with a new email address (gmail) and then everything works fine.

Using a Yahoo!Mail account to do 2FA used to work, but now I am getting the same error as above. I tried to created an account using gmail, but I am getting the following error: imap connection failedb'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'. I have set up the gmail account to accept IMAP.

I also tried to use push notifications, but I am getting the following error: error in new response={'meta': {'code': 400, 'error': 9233, 'message': 'Authentication is not finished yet'}}. I never get a push notification on my phone.

The username / password seems to be correct because when I set the wrong password, I get a different error: error in new response={'meta': {'code': 403, 'error': 9017, 'message': 'Account locked'}}

Anyone has any suggestions?

**Comment by orandasoft** [comment]
Yahoo has confirmed to me that app password feature is currently not available and there is no ETA for it to return.

Google help states: _To help keep your account secure, from May 30, 2022, ​​Google no longer supports the use of third-party apps or devices which ask you to sign in to your Google Account using only your username and password._

How do I get 2FA to work?

**Comment by orandasoft** [comment]
I got push notifications to work. I assumed that I needed to use my main Arlo account I use on my phone to receive push notifications. I used this account in the configuration file and couldn't get it work. Then I used a delegated account and it worked on first bat. Not sure whether using a delegated account was the issue, but I am not going to complain.

**Comment by twrecked** [comment]
I should be able to get the oauth authentication to work. I already have a helper app running in the cloud I can probably expand that to make it work.

I figure I'll need it sooner rather than later...

**Comment by twrecked** [comment]
@orandasoft 

Can you try creating an app password for gmail? My reading of that notice was it applies to trying to login with your main password, especially when it's backed by 2fa. I can still create an app password for my gmail accounts.

https://support.google.com/mail/answer/185833?hl=en

But my Yahoo! account can't create app passwords.

**Comment by orandasoft** [comment]
@twrecked 

I can confirm that I was able to start aarlo with the gmail account and account password. 2-step-verification was not enabled for the gmail account. When 2-step-verification is not enabled, the option to generate an app password is **not** available.

After enabling the 2-step-verification for the account, the option to generate an app password became available. I generated an app password for aarlo and used it successfully.

Thanks for pointing this out.

P.S.
I see a lot (every 3 seconds) a debug message from pyaarlo:
2022-10-15 14:59:51.051 DEBUG (ArloEventStream) [pyaarlo] mqtt: connected=0
2022-10-15 14:59:51.052 DEBUG (ArloEventStream) [pyaarlo] topcs=
[]

**Comment by twrecked** [comment]
Change the backend to "sse" to fix the mqtt issue.

I'm not at my computer but the readme will tell you how to do it.

**Comment by orandasoft** [comment]
Added backend: sse to the configuration file and do not see the above debug messages related to mqtt anymore.

**Comment by heap73** [comment]
Good afternoon everyone, hope you can help. I did setup my aarlo integration and it works using 2FA on Mobile App (with 2 accounts configured). Only issue is that i keep receiving many notification on my app to approve the login. Anyone experiencing the same? how can I fix it? Thanks
