### ISSUE TITLE
TFA - imap connection failed[Errno -2] Name does not resolve

### ISSUE THREAD

**Issue by KalleHoppe** [twrecked/hass-aarlo#796]
Hi, i want to start by thanking @twrecked for all the great work and effort into this project. 
I was one of the many that had issues with the 2fa changes solved in issue #778, and I got it working... for some time, until sometime this week when i started to get this error in the logs during 2fa authentication process:

```code
imap connection failed[Errno -2] Name does not resolve
2fa startup failed
```
I suppose it can't resolve the imap url for the API, but I don't know for sure that is the url that is failing.
How can I find the has-aarlo logs so I can verify? I can only manage to see the HA logs, not the detailed ones. 
Is there any one else getting this issue?

My configuration looks like this:
```yaml
aarlo:
  username: !secret arlo_gmail_username
  password: !secret arlo_password
  mode_api: auto
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90
  tfa_username: !secret arlo_gmail_username
  tfa_password: !secret arlo_gmail_app_password
  verbose_debug: True

  tfa_source: imap
  tfa_type: email
  host: https://my.arlo.com
```

**Comment by twrecked** [comment]
It looks like a resolver issue. What is your `tfa_host` set to?

**Comment by KalleHoppe** [comment]
Yeah, exactly.
I was told in the other 2-fa thread to remove the tfa_host property from the config, so I only have the host property set as in my comment.
Should I have both host and tfa_host configured?

**Comment by twrecked** [comment]
Yes. One configures authentication with Arlo and the second one tells us
how to collect the 2FA code that authentication generates.

You don't usually need to change the non tfa one.

**Comment by KalleHoppe** [comment]
ok, thanks for the explanation. 
I added the tfa_host: imap.gmail.com. So the config looks like this now
````yaml
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  mode_api: auto
  refresh_devices_every: 2
  stream_timeout: 120
  reconnect_every: 90
  tfa_username: !secret arlo_gmail_username
  tfa_password: !secret arlo_gmail_app_password
  verbose_debug: True

  tfa_source: imap
  tfa_type: email
  host: https://my.arlo.com
  tfa_host: imap.gmail.com
````
to the config, but now I'm getting this error, below. So I guess I'm back to the same issue as in #778. Sorry I can't find a more detailed error message in the logs :/
```code
body-error=JSONDecodeError
authentication failed
```

**Comment by KalleHoppe** [comment]
Ok, this is wierd. Even though I got that json error, it now seems that the authentication was successful and it's working again! I haven't done anything since my previous message.

**Comment by ramdisk00** [comment]
I also have issues with aarlo / arlo, it stopped working a month or so with the tfa thing. I followed the recommendations modifying background file in both spots and setup the google email tfa, no luck here. Not sure where to start to look to see if tfa is working.

this is one of my errors:

```
body-error=JSONDecodeError
No locations returned from /hmsdevicemanagement/users/5HS5-336-66351581/locations
```


this is my alro config

```
aarlo:
  host: https://my.arlo.com
  username: !secret arlo_ha_user
  password: !secret arlo_ha_password
  mode_api: auto
  verbose_debug: True
  tfa_source: imap
  tfa_type: email
  tfa_host: imap.gmail.com
  tfa_username: !secret arlo_tfa_user
  tfa_password: !secret arlo_tfa_password
```

I also get "unavailable" on all of my arlo entities, which in the past I did not get.

**Comment by KalleHoppe** [comment]
Do you het a OTP email to your email account? If no, then the email/app password might be the issue. 

The "unavailiable" is because the aarlo component didn't load (probably because of the authentication issue).

Did you do a complete hardware reboot after the reconfiguration and removing the pickle files? There could be a caching issue. In system, go to the restart, then Advanced an do a system reboot.

**Comment by ramdisk00** [comment]
not sure what het or OTP are? I did remove both aarlo.pickle and session.pickle files. I'll try again with a arlo hardware restart. Thanks

**Comment by KalleHoppe** [comment]
The OTP (One Time Password) is the code you get in the email from Arlo when you ( or this aarlo component) tries to login to the Arlo service. It's the second factor in the 2-factor authentication.

BTW, when i said reboot, I meant reboot home assistant, not the Arlo hub. 
Hope it works out

**Comment by SebSkarp** [comment]
> The OTP (One Time Password) is the code you get in the email from Arlo when you ( or this aarlo component) tries to login to the Arlo service. It's the second factor in the 2-factor authentication.
> 
> BTW, when i said reboot, I meant reboot home assistant, not the Arlo hub. Hope it works out

Hey
I have issues here too, since some weeks ago. In my case I do get the OTP emails to my gmail, every time HA restarts and the Arlo integration tries to startup.

However, I get this error shown in the logs. Something too with 2FA, but I don't know what really...making it hard to try to resolve.
You/anyone else having any idea on what to try? To me it almost seems like the Arlo integration cannot access my gmail all of the sudden, but to my knowledge nothing changed. Was working with no issues for a very long time.

Log:
Felet härrör från en anpassad integration.

Logger: pyaarlo
Source: custom_components/aarlo/pyaarlo/__init__.py:165
Integration: aarlo (documentation, issues) 
First occurred: 21:55:36 (4 occurrences) 
Last logged: 22:00:36

2fa core retrieval failed

Config:

############Arlo  
aarlo:
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
  tfa_host: imap.gmail.com
  tfa_username: !secret tfa_username
  tfa_password: !secret tfa_password
  backend: sse
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 0

Any input/help would be much appreciated. Need to get the integration working again =/

Thanks

**Comment by KalleHoppe** [comment]
Frlm a quick glance on your config you are missing the host atribute and value:
`host: https://my.arlo.com/`

**Comment by KalleHoppe** [comment]
I'm closing this issue, since it was caused by misconfiguration, and solved by defining both `host `and `tfa_host` in the config.

**Comment by SebSkarp** [comment]
Hi again
I added the value you mentioned @KalleHoppe but it still won't work. When checking the gmail configured for the tfa codes I do see those are coming.
This is my current config. Do I need to edit it more?

Thanks

aarlo:
  host: https://my.arlo.com/
  username: !secret arlo_username
  password: !secret arlo_password
  refresh_devices_every: 2
  stream_timeout: 120
  tfa_host: imap.gmail.com
  tfa_username: !secret tfa_username
  tfa_password: !secret tfa_password
  backend: sse
  
alarm_control_panel:
  - platform: aarlo
    away_mode_name: armed
    home_mode_name: home
    night_mode_name: night
    trigger_time: 30
    alarm_volume: 0
